package com.qingxun.pub.generate.pojo;

public class AppCarouselKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_carousel._id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_carousel.car_id
     *
     * @mbg.generated
     */
    private Integer carId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_carousel._id
     *
     * @return the value of app_carousel._id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_carousel._id
     *
     * @param id the value for app_carousel._id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_carousel.car_id
     *
     * @return the value of app_carousel.car_id
     *
     * @mbg.generated
     */
    public Integer getCarId() {
        return carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_carousel.car_id
     *
     * @param carId the value for app_carousel.car_id
     *
     * @mbg.generated
     */
    public void setCarId(Integer carId) {
        this.carId = carId;
    }
}