package com.qingxun.pub.generate.pojo;

import java.util.Date;

public class AppCarousel extends AppCarouselKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_carousel.car_imgurl
     *
     * @mbg.generated
     */
    private String carImgurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_carousel.car_content
     *
     * @mbg.generated
     */
    private String carContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_carousel.car_activity
     *
     * @mbg.generated
     */
    private String carActivity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_carousel.car_time
     *
     * @mbg.generated
     */
    private Date carTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_carousel.car_imgurl
     *
     * @return the value of app_carousel.car_imgurl
     *
     * @mbg.generated
     */
    public String getCarImgurl() {
        return carImgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_carousel.car_imgurl
     *
     * @param carImgurl the value for app_carousel.car_imgurl
     *
     * @mbg.generated
     */
    public void setCarImgurl(String carImgurl) {
        this.carImgurl = carImgurl == null ? null : carImgurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_carousel.car_content
     *
     * @return the value of app_carousel.car_content
     *
     * @mbg.generated
     */
    public String getCarContent() {
        return carContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_carousel.car_content
     *
     * @param carContent the value for app_carousel.car_content
     *
     * @mbg.generated
     */
    public void setCarContent(String carContent) {
        this.carContent = carContent == null ? null : carContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_carousel.car_activity
     *
     * @return the value of app_carousel.car_activity
     *
     * @mbg.generated
     */
    public String getCarActivity() {
        return carActivity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_carousel.car_activity
     *
     * @param carActivity the value for app_carousel.car_activity
     *
     * @mbg.generated
     */
    public void setCarActivity(String carActivity) {
        this.carActivity = carActivity == null ? null : carActivity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_carousel.car_time
     *
     * @return the value of app_carousel.car_time
     *
     * @mbg.generated
     */
    public Date getCarTime() {
        return carTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_carousel.car_time
     *
     * @param carTime the value for app_carousel.car_time
     *
     * @mbg.generated
     */
    public void setCarTime(Date carTime) {
        this.carTime = carTime;
    }
}