package com.qingxun.pub.generate.pojo;

import java.util.ArrayList;
import java.util.List;

public class CommodityType2Example {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table commodity_type2
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table commodity_type2
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table commodity_type2
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_type2
     *
     * @mbg.generated
     */
    public CommodityType2Example() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_type2
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_type2
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_type2
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_type2
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_type2
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_type2
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_type2
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_type2
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_type2
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_type2
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table commodity_type2
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("_id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("_id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("_id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("_id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("_id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("_id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("_id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("_id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("_id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("_id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("_id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("_id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andType2IdIsNull() {
            addCriterion("type2_id is null");
            return (Criteria) this;
        }

        public Criteria andType2IdIsNotNull() {
            addCriterion("type2_id is not null");
            return (Criteria) this;
        }

        public Criteria andType2IdEqualTo(Integer value) {
            addCriterion("type2_id =", value, "type2Id");
            return (Criteria) this;
        }

        public Criteria andType2IdNotEqualTo(Integer value) {
            addCriterion("type2_id <>", value, "type2Id");
            return (Criteria) this;
        }

        public Criteria andType2IdGreaterThan(Integer value) {
            addCriterion("type2_id >", value, "type2Id");
            return (Criteria) this;
        }

        public Criteria andType2IdGreaterThanOrEqualTo(Integer value) {
            addCriterion("type2_id >=", value, "type2Id");
            return (Criteria) this;
        }

        public Criteria andType2IdLessThan(Integer value) {
            addCriterion("type2_id <", value, "type2Id");
            return (Criteria) this;
        }

        public Criteria andType2IdLessThanOrEqualTo(Integer value) {
            addCriterion("type2_id <=", value, "type2Id");
            return (Criteria) this;
        }

        public Criteria andType2IdIn(List<Integer> values) {
            addCriterion("type2_id in", values, "type2Id");
            return (Criteria) this;
        }

        public Criteria andType2IdNotIn(List<Integer> values) {
            addCriterion("type2_id not in", values, "type2Id");
            return (Criteria) this;
        }

        public Criteria andType2IdBetween(Integer value1, Integer value2) {
            addCriterion("type2_id between", value1, value2, "type2Id");
            return (Criteria) this;
        }

        public Criteria andType2IdNotBetween(Integer value1, Integer value2) {
            addCriterion("type2_id not between", value1, value2, "type2Id");
            return (Criteria) this;
        }

        public Criteria andType1IdIsNull() {
            addCriterion("type1_id is null");
            return (Criteria) this;
        }

        public Criteria andType1IdIsNotNull() {
            addCriterion("type1_id is not null");
            return (Criteria) this;
        }

        public Criteria andType1IdEqualTo(Integer value) {
            addCriterion("type1_id =", value, "type1Id");
            return (Criteria) this;
        }

        public Criteria andType1IdNotEqualTo(Integer value) {
            addCriterion("type1_id <>", value, "type1Id");
            return (Criteria) this;
        }

        public Criteria andType1IdGreaterThan(Integer value) {
            addCriterion("type1_id >", value, "type1Id");
            return (Criteria) this;
        }

        public Criteria andType1IdGreaterThanOrEqualTo(Integer value) {
            addCriterion("type1_id >=", value, "type1Id");
            return (Criteria) this;
        }

        public Criteria andType1IdLessThan(Integer value) {
            addCriterion("type1_id <", value, "type1Id");
            return (Criteria) this;
        }

        public Criteria andType1IdLessThanOrEqualTo(Integer value) {
            addCriterion("type1_id <=", value, "type1Id");
            return (Criteria) this;
        }

        public Criteria andType1IdIn(List<Integer> values) {
            addCriterion("type1_id in", values, "type1Id");
            return (Criteria) this;
        }

        public Criteria andType1IdNotIn(List<Integer> values) {
            addCriterion("type1_id not in", values, "type1Id");
            return (Criteria) this;
        }

        public Criteria andType1IdBetween(Integer value1, Integer value2) {
            addCriterion("type1_id between", value1, value2, "type1Id");
            return (Criteria) this;
        }

        public Criteria andType1IdNotBetween(Integer value1, Integer value2) {
            addCriterion("type1_id not between", value1, value2, "type1Id");
            return (Criteria) this;
        }

        public Criteria andType2NameIsNull() {
            addCriterion("type2_name is null");
            return (Criteria) this;
        }

        public Criteria andType2NameIsNotNull() {
            addCriterion("type2_name is not null");
            return (Criteria) this;
        }

        public Criteria andType2NameEqualTo(String value) {
            addCriterion("type2_name =", value, "type2Name");
            return (Criteria) this;
        }

        public Criteria andType2NameNotEqualTo(String value) {
            addCriterion("type2_name <>", value, "type2Name");
            return (Criteria) this;
        }

        public Criteria andType2NameGreaterThan(String value) {
            addCriterion("type2_name >", value, "type2Name");
            return (Criteria) this;
        }

        public Criteria andType2NameGreaterThanOrEqualTo(String value) {
            addCriterion("type2_name >=", value, "type2Name");
            return (Criteria) this;
        }

        public Criteria andType2NameLessThan(String value) {
            addCriterion("type2_name <", value, "type2Name");
            return (Criteria) this;
        }

        public Criteria andType2NameLessThanOrEqualTo(String value) {
            addCriterion("type2_name <=", value, "type2Name");
            return (Criteria) this;
        }

        public Criteria andType2NameLike(String value) {
            addCriterion("type2_name like", value, "type2Name");
            return (Criteria) this;
        }

        public Criteria andType2NameNotLike(String value) {
            addCriterion("type2_name not like", value, "type2Name");
            return (Criteria) this;
        }

        public Criteria andType2NameIn(List<String> values) {
            addCriterion("type2_name in", values, "type2Name");
            return (Criteria) this;
        }

        public Criteria andType2NameNotIn(List<String> values) {
            addCriterion("type2_name not in", values, "type2Name");
            return (Criteria) this;
        }

        public Criteria andType2NameBetween(String value1, String value2) {
            addCriterion("type2_name between", value1, value2, "type2Name");
            return (Criteria) this;
        }

        public Criteria andType2NameNotBetween(String value1, String value2) {
            addCriterion("type2_name not between", value1, value2, "type2Name");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table commodity_type2
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table commodity_type2
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}