package com.qingxun.pub.generate.pojo;

public class Commodity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity._id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.mar_id
     *
     * @mbg.generated
     */
    private Integer marId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.com_id
     *
     * @mbg.generated
     */
    private Integer comId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.com_imgurl
     *
     * @mbg.generated
     */
    private String comImgurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.com_struts
     *
     * @mbg.generated
     */
    private String comStruts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.com_top
     *
     * @mbg.generated
     */
    private Integer comTop;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.com_typy_id1
     *
     * @mbg.generated
     */
    private Integer comTypyId1;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity._id
     *
     * @return the value of commodity._id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity._id
     *
     * @param id the value for commodity._id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.mar_id
     *
     * @return the value of commodity.mar_id
     *
     * @mbg.generated
     */
    public Integer getMarId() {
        return marId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.mar_id
     *
     * @param marId the value for commodity.mar_id
     *
     * @mbg.generated
     */
    public void setMarId(Integer marId) {
        this.marId = marId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.com_id
     *
     * @return the value of commodity.com_id
     *
     * @mbg.generated
     */
    public Integer getComId() {
        return comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.com_id
     *
     * @param comId the value for commodity.com_id
     *
     * @mbg.generated
     */
    public void setComId(Integer comId) {
        this.comId = comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.com_imgurl
     *
     * @return the value of commodity.com_imgurl
     *
     * @mbg.generated
     */
    public String getComImgurl() {
        return comImgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.com_imgurl
     *
     * @param comImgurl the value for commodity.com_imgurl
     *
     * @mbg.generated
     */
    public void setComImgurl(String comImgurl) {
        this.comImgurl = comImgurl == null ? null : comImgurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.com_struts
     *
     * @return the value of commodity.com_struts
     *
     * @mbg.generated
     */
    public String getComStruts() {
        return comStruts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.com_struts
     *
     * @param comStruts the value for commodity.com_struts
     *
     * @mbg.generated
     */
    public void setComStruts(String comStruts) {
        this.comStruts = comStruts == null ? null : comStruts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.com_top
     *
     * @return the value of commodity.com_top
     *
     * @mbg.generated
     */
    public Integer getComTop() {
        return comTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.com_top
     *
     * @param comTop the value for commodity.com_top
     *
     * @mbg.generated
     */
    public void setComTop(Integer comTop) {
        this.comTop = comTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.com_typy_id1
     *
     * @return the value of commodity.com_typy_id1
     *
     * @mbg.generated
     */
    public Integer getComTypyId1() {
        return comTypyId1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.com_typy_id1
     *
     * @param comTypyId1 the value for commodity.com_typy_id1
     *
     * @mbg.generated
     */
    public void setComTypyId1(Integer comTypyId1) {
        this.comTypyId1 = comTypyId1;
    }
}