package com.qingxun.pub.generate.pojo;

public class Indent extends IndentKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indent.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indent.com_id
     *
     * @mbg.generated
     */
    private Integer comId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indent.ind_sturts
     *
     * @mbg.generated
     */
    private Integer indSturts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indent.com_num
     *
     * @mbg.generated
     */
    private Integer comNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indent.mer_id
     *
     * @mbg.generated
     */
    private Integer merId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indent.user_id
     *
     * @return the value of indent.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indent.user_id
     *
     * @param userId the value for indent.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indent.com_id
     *
     * @return the value of indent.com_id
     *
     * @mbg.generated
     */
    public Integer getComId() {
        return comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indent.com_id
     *
     * @param comId the value for indent.com_id
     *
     * @mbg.generated
     */
    public void setComId(Integer comId) {
        this.comId = comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indent.ind_sturts
     *
     * @return the value of indent.ind_sturts
     *
     * @mbg.generated
     */
    public Integer getIndSturts() {
        return indSturts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indent.ind_sturts
     *
     * @param indSturts the value for indent.ind_sturts
     *
     * @mbg.generated
     */
    public void setIndSturts(Integer indSturts) {
        this.indSturts = indSturts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indent.com_num
     *
     * @return the value of indent.com_num
     *
     * @mbg.generated
     */
    public Integer getComNum() {
        return comNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indent.com_num
     *
     * @param comNum the value for indent.com_num
     *
     * @mbg.generated
     */
    public void setComNum(Integer comNum) {
        this.comNum = comNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indent.mer_id
     *
     * @return the value of indent.mer_id
     *
     * @mbg.generated
     */
    public Integer getMerId() {
        return merId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indent.mer_id
     *
     * @param merId the value for indent.mer_id
     *
     * @mbg.generated
     */
    public void setMerId(Integer merId) {
        this.merId = merId;
    }
}