package com.qingxun.pub.generate.pojo;

import java.util.ArrayList;
import java.util.List;

public class IndentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table indent
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table indent
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table indent
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indent
     *
     * @mbg.generated
     */
    public IndentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indent
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indent
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indent
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indent
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indent
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indent
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indent
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indent
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indent
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indent
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table indent
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("_id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("_id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("_id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("_id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("_id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("_id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("_id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("_id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("_id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("_id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("_id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("_id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIndIdIsNull() {
            addCriterion("ind_id is null");
            return (Criteria) this;
        }

        public Criteria andIndIdIsNotNull() {
            addCriterion("ind_id is not null");
            return (Criteria) this;
        }

        public Criteria andIndIdEqualTo(Integer value) {
            addCriterion("ind_id =", value, "indId");
            return (Criteria) this;
        }

        public Criteria andIndIdNotEqualTo(Integer value) {
            addCriterion("ind_id <>", value, "indId");
            return (Criteria) this;
        }

        public Criteria andIndIdGreaterThan(Integer value) {
            addCriterion("ind_id >", value, "indId");
            return (Criteria) this;
        }

        public Criteria andIndIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ind_id >=", value, "indId");
            return (Criteria) this;
        }

        public Criteria andIndIdLessThan(Integer value) {
            addCriterion("ind_id <", value, "indId");
            return (Criteria) this;
        }

        public Criteria andIndIdLessThanOrEqualTo(Integer value) {
            addCriterion("ind_id <=", value, "indId");
            return (Criteria) this;
        }

        public Criteria andIndIdIn(List<Integer> values) {
            addCriterion("ind_id in", values, "indId");
            return (Criteria) this;
        }

        public Criteria andIndIdNotIn(List<Integer> values) {
            addCriterion("ind_id not in", values, "indId");
            return (Criteria) this;
        }

        public Criteria andIndIdBetween(Integer value1, Integer value2) {
            addCriterion("ind_id between", value1, value2, "indId");
            return (Criteria) this;
        }

        public Criteria andIndIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ind_id not between", value1, value2, "indId");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andComIdIsNull() {
            addCriterion("com_id is null");
            return (Criteria) this;
        }

        public Criteria andComIdIsNotNull() {
            addCriterion("com_id is not null");
            return (Criteria) this;
        }

        public Criteria andComIdEqualTo(Integer value) {
            addCriterion("com_id =", value, "comId");
            return (Criteria) this;
        }

        public Criteria andComIdNotEqualTo(Integer value) {
            addCriterion("com_id <>", value, "comId");
            return (Criteria) this;
        }

        public Criteria andComIdGreaterThan(Integer value) {
            addCriterion("com_id >", value, "comId");
            return (Criteria) this;
        }

        public Criteria andComIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("com_id >=", value, "comId");
            return (Criteria) this;
        }

        public Criteria andComIdLessThan(Integer value) {
            addCriterion("com_id <", value, "comId");
            return (Criteria) this;
        }

        public Criteria andComIdLessThanOrEqualTo(Integer value) {
            addCriterion("com_id <=", value, "comId");
            return (Criteria) this;
        }

        public Criteria andComIdIn(List<Integer> values) {
            addCriterion("com_id in", values, "comId");
            return (Criteria) this;
        }

        public Criteria andComIdNotIn(List<Integer> values) {
            addCriterion("com_id not in", values, "comId");
            return (Criteria) this;
        }

        public Criteria andComIdBetween(Integer value1, Integer value2) {
            addCriterion("com_id between", value1, value2, "comId");
            return (Criteria) this;
        }

        public Criteria andComIdNotBetween(Integer value1, Integer value2) {
            addCriterion("com_id not between", value1, value2, "comId");
            return (Criteria) this;
        }

        public Criteria andIndSturtsIsNull() {
            addCriterion("ind_sturts is null");
            return (Criteria) this;
        }

        public Criteria andIndSturtsIsNotNull() {
            addCriterion("ind_sturts is not null");
            return (Criteria) this;
        }

        public Criteria andIndSturtsEqualTo(Integer value) {
            addCriterion("ind_sturts =", value, "indSturts");
            return (Criteria) this;
        }

        public Criteria andIndSturtsNotEqualTo(Integer value) {
            addCriterion("ind_sturts <>", value, "indSturts");
            return (Criteria) this;
        }

        public Criteria andIndSturtsGreaterThan(Integer value) {
            addCriterion("ind_sturts >", value, "indSturts");
            return (Criteria) this;
        }

        public Criteria andIndSturtsGreaterThanOrEqualTo(Integer value) {
            addCriterion("ind_sturts >=", value, "indSturts");
            return (Criteria) this;
        }

        public Criteria andIndSturtsLessThan(Integer value) {
            addCriterion("ind_sturts <", value, "indSturts");
            return (Criteria) this;
        }

        public Criteria andIndSturtsLessThanOrEqualTo(Integer value) {
            addCriterion("ind_sturts <=", value, "indSturts");
            return (Criteria) this;
        }

        public Criteria andIndSturtsIn(List<Integer> values) {
            addCriterion("ind_sturts in", values, "indSturts");
            return (Criteria) this;
        }

        public Criteria andIndSturtsNotIn(List<Integer> values) {
            addCriterion("ind_sturts not in", values, "indSturts");
            return (Criteria) this;
        }

        public Criteria andIndSturtsBetween(Integer value1, Integer value2) {
            addCriterion("ind_sturts between", value1, value2, "indSturts");
            return (Criteria) this;
        }

        public Criteria andIndSturtsNotBetween(Integer value1, Integer value2) {
            addCriterion("ind_sturts not between", value1, value2, "indSturts");
            return (Criteria) this;
        }

        public Criteria andComNumIsNull() {
            addCriterion("com_num is null");
            return (Criteria) this;
        }

        public Criteria andComNumIsNotNull() {
            addCriterion("com_num is not null");
            return (Criteria) this;
        }

        public Criteria andComNumEqualTo(Integer value) {
            addCriterion("com_num =", value, "comNum");
            return (Criteria) this;
        }

        public Criteria andComNumNotEqualTo(Integer value) {
            addCriterion("com_num <>", value, "comNum");
            return (Criteria) this;
        }

        public Criteria andComNumGreaterThan(Integer value) {
            addCriterion("com_num >", value, "comNum");
            return (Criteria) this;
        }

        public Criteria andComNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("com_num >=", value, "comNum");
            return (Criteria) this;
        }

        public Criteria andComNumLessThan(Integer value) {
            addCriterion("com_num <", value, "comNum");
            return (Criteria) this;
        }

        public Criteria andComNumLessThanOrEqualTo(Integer value) {
            addCriterion("com_num <=", value, "comNum");
            return (Criteria) this;
        }

        public Criteria andComNumIn(List<Integer> values) {
            addCriterion("com_num in", values, "comNum");
            return (Criteria) this;
        }

        public Criteria andComNumNotIn(List<Integer> values) {
            addCriterion("com_num not in", values, "comNum");
            return (Criteria) this;
        }

        public Criteria andComNumBetween(Integer value1, Integer value2) {
            addCriterion("com_num between", value1, value2, "comNum");
            return (Criteria) this;
        }

        public Criteria andComNumNotBetween(Integer value1, Integer value2) {
            addCriterion("com_num not between", value1, value2, "comNum");
            return (Criteria) this;
        }

        public Criteria andMerIdIsNull() {
            addCriterion("mer_id is null");
            return (Criteria) this;
        }

        public Criteria andMerIdIsNotNull() {
            addCriterion("mer_id is not null");
            return (Criteria) this;
        }

        public Criteria andMerIdEqualTo(Integer value) {
            addCriterion("mer_id =", value, "merId");
            return (Criteria) this;
        }

        public Criteria andMerIdNotEqualTo(Integer value) {
            addCriterion("mer_id <>", value, "merId");
            return (Criteria) this;
        }

        public Criteria andMerIdGreaterThan(Integer value) {
            addCriterion("mer_id >", value, "merId");
            return (Criteria) this;
        }

        public Criteria andMerIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("mer_id >=", value, "merId");
            return (Criteria) this;
        }

        public Criteria andMerIdLessThan(Integer value) {
            addCriterion("mer_id <", value, "merId");
            return (Criteria) this;
        }

        public Criteria andMerIdLessThanOrEqualTo(Integer value) {
            addCriterion("mer_id <=", value, "merId");
            return (Criteria) this;
        }

        public Criteria andMerIdIn(List<Integer> values) {
            addCriterion("mer_id in", values, "merId");
            return (Criteria) this;
        }

        public Criteria andMerIdNotIn(List<Integer> values) {
            addCriterion("mer_id not in", values, "merId");
            return (Criteria) this;
        }

        public Criteria andMerIdBetween(Integer value1, Integer value2) {
            addCriterion("mer_id between", value1, value2, "merId");
            return (Criteria) this;
        }

        public Criteria andMerIdNotBetween(Integer value1, Integer value2) {
            addCriterion("mer_id not between", value1, value2, "merId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table indent
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table indent
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}