package com.qingxun.pub.generate.pojo;

public class IndentKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indent._id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indent.ind_id
     *
     * @mbg.generated
     */
    private Integer indId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indent._id
     *
     * @return the value of indent._id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indent._id
     *
     * @param id the value for indent._id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indent.ind_id
     *
     * @return the value of indent.ind_id
     *
     * @mbg.generated
     */
    public Integer getIndId() {
        return indId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indent.ind_id
     *
     * @param indId the value for indent.ind_id
     *
     * @mbg.generated
     */
    public void setIndId(Integer indId) {
        this.indId = indId;
    }
}