package com.qingxun.pub.generate.pojo;

public class MissionJpuz {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission_jpuz._id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission_jpuz.jpuz_id
     *
     * @mbg.generated
     */
    private Integer jpuzId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission_jpuz.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission_jpuz.jpuz_time
     *
     * @mbg.generated
     */
    private String jpuzTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission_jpuz.jpuz_sturts
     *
     * @mbg.generated
     */
    private String jpuzSturts;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission_jpuz._id
     *
     * @return the value of mission_jpuz._id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission_jpuz._id
     *
     * @param id the value for mission_jpuz._id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission_jpuz.jpuz_id
     *
     * @return the value of mission_jpuz.jpuz_id
     *
     * @mbg.generated
     */
    public Integer getJpuzId() {
        return jpuzId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission_jpuz.jpuz_id
     *
     * @param jpuzId the value for mission_jpuz.jpuz_id
     *
     * @mbg.generated
     */
    public void setJpuzId(Integer jpuzId) {
        this.jpuzId = jpuzId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission_jpuz.user_id
     *
     * @return the value of mission_jpuz.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission_jpuz.user_id
     *
     * @param userId the value for mission_jpuz.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission_jpuz.jpuz_time
     *
     * @return the value of mission_jpuz.jpuz_time
     *
     * @mbg.generated
     */
    public String getJpuzTime() {
        return jpuzTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission_jpuz.jpuz_time
     *
     * @param jpuzTime the value for mission_jpuz.jpuz_time
     *
     * @mbg.generated
     */
    public void setJpuzTime(String jpuzTime) {
        this.jpuzTime = jpuzTime == null ? null : jpuzTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission_jpuz.jpuz_sturts
     *
     * @return the value of mission_jpuz.jpuz_sturts
     *
     * @mbg.generated
     */
    public String getJpuzSturts() {
        return jpuzSturts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission_jpuz.jpuz_sturts
     *
     * @param jpuzSturts the value for mission_jpuz.jpuz_sturts
     *
     * @mbg.generated
     */
    public void setJpuzSturts(String jpuzSturts) {
        this.jpuzSturts = jpuzSturts == null ? null : jpuzSturts.trim();
    }
}