package com.qingxun.pub.generate.pojo;

public class Mission {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission._id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.mis_id
     *
     * @mbg.generated
     */
    private Integer misId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.faqi_id
     *
     * @mbg.generated
     */
    private Integer faqiId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.jpuz_id
     *
     * @mbg.generated
     */
    private Integer jpuzId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.mis_tilte
     *
     * @mbg.generated
     */
    private String misTilte;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.mis_content
     *
     * @mbg.generated
     */
    private String misContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.mis_time1
     *
     * @mbg.generated
     */
    private String misTime1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.mis_time2
     *
     * @mbg.generated
     */
    private String misTime2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.mis_struts
     *
     * @mbg.generated
     */
    private Integer misStruts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.mis_xuqqnum
     *
     * @mbg.generated
     */
    private Integer misXuqqnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.mis_money
     *
     * @mbg.generated
     */
    private Float misMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.mis_top
     *
     * @mbg.generated
     */
    private Integer misTop;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission._id
     *
     * @return the value of mission._id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission._id
     *
     * @param id the value for mission._id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission.mis_id
     *
     * @return the value of mission.mis_id
     *
     * @mbg.generated
     */
    public Integer getMisId() {
        return misId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission.mis_id
     *
     * @param misId the value for mission.mis_id
     *
     * @mbg.generated
     */
    public void setMisId(Integer misId) {
        this.misId = misId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission.faqi_id
     *
     * @return the value of mission.faqi_id
     *
     * @mbg.generated
     */
    public Integer getFaqiId() {
        return faqiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission.faqi_id
     *
     * @param faqiId the value for mission.faqi_id
     *
     * @mbg.generated
     */
    public void setFaqiId(Integer faqiId) {
        this.faqiId = faqiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission.jpuz_id
     *
     * @return the value of mission.jpuz_id
     *
     * @mbg.generated
     */
    public Integer getJpuzId() {
        return jpuzId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission.jpuz_id
     *
     * @param jpuzId the value for mission.jpuz_id
     *
     * @mbg.generated
     */
    public void setJpuzId(Integer jpuzId) {
        this.jpuzId = jpuzId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission.mis_tilte
     *
     * @return the value of mission.mis_tilte
     *
     * @mbg.generated
     */
    public String getMisTilte() {
        return misTilte;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission.mis_tilte
     *
     * @param misTilte the value for mission.mis_tilte
     *
     * @mbg.generated
     */
    public void setMisTilte(String misTilte) {
        this.misTilte = misTilte == null ? null : misTilte.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission.mis_content
     *
     * @return the value of mission.mis_content
     *
     * @mbg.generated
     */
    public String getMisContent() {
        return misContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission.mis_content
     *
     * @param misContent the value for mission.mis_content
     *
     * @mbg.generated
     */
    public void setMisContent(String misContent) {
        this.misContent = misContent == null ? null : misContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission.mis_time1
     *
     * @return the value of mission.mis_time1
     *
     * @mbg.generated
     */
    public String getMisTime1() {
        return misTime1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission.mis_time1
     *
     * @param misTime1 the value for mission.mis_time1
     *
     * @mbg.generated
     */
    public void setMisTime1(String misTime1) {
        this.misTime1 = misTime1 == null ? null : misTime1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission.mis_time2
     *
     * @return the value of mission.mis_time2
     *
     * @mbg.generated
     */
    public String getMisTime2() {
        return misTime2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission.mis_time2
     *
     * @param misTime2 the value for mission.mis_time2
     *
     * @mbg.generated
     */
    public void setMisTime2(String misTime2) {
        this.misTime2 = misTime2 == null ? null : misTime2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission.mis_struts
     *
     * @return the value of mission.mis_struts
     *
     * @mbg.generated
     */
    public Integer getMisStruts() {
        return misStruts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission.mis_struts
     *
     * @param misStruts the value for mission.mis_struts
     *
     * @mbg.generated
     */
    public void setMisStruts(Integer misStruts) {
        this.misStruts = misStruts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission.mis_xuqqnum
     *
     * @return the value of mission.mis_xuqqnum
     *
     * @mbg.generated
     */
    public Integer getMisXuqqnum() {
        return misXuqqnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission.mis_xuqqnum
     *
     * @param misXuqqnum the value for mission.mis_xuqqnum
     *
     * @mbg.generated
     */
    public void setMisXuqqnum(Integer misXuqqnum) {
        this.misXuqqnum = misXuqqnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission.mis_money
     *
     * @return the value of mission.mis_money
     *
     * @mbg.generated
     */
    public Float getMisMoney() {
        return misMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission.mis_money
     *
     * @param misMoney the value for mission.mis_money
     *
     * @mbg.generated
     */
    public void setMisMoney(Float misMoney) {
        this.misMoney = misMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission.mis_top
     *
     * @return the value of mission.mis_top
     *
     * @mbg.generated
     */
    public Integer getMisTop() {
        return misTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission.mis_top
     *
     * @param misTop the value for mission.mis_top
     *
     * @mbg.generated
     */
    public void setMisTop(Integer misTop) {
        this.misTop = misTop;
    }
}