package com.qingxun.pub.generate.pojo;

public class UserAdmin extends UserAdminKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_admin.admin_login
     *
     * @mbg.generated
     */
    private String adminLogin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_admin.admin_psd
     *
     * @mbg.generated
     */
    private String adminPsd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_admin.admin_name
     *
     * @mbg.generated
     */
    private String adminName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_admin.admin_login
     *
     * @return the value of user_admin.admin_login
     *
     * @mbg.generated
     */
    public String getAdminLogin() {
        return adminLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_admin.admin_login
     *
     * @param adminLogin the value for user_admin.admin_login
     *
     * @mbg.generated
     */
    public void setAdminLogin(String adminLogin) {
        this.adminLogin = adminLogin == null ? null : adminLogin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_admin.admin_psd
     *
     * @return the value of user_admin.admin_psd
     *
     * @mbg.generated
     */
    public String getAdminPsd() {
        return adminPsd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_admin.admin_psd
     *
     * @param adminPsd the value for user_admin.admin_psd
     *
     * @mbg.generated
     */
    public void setAdminPsd(String adminPsd) {
        this.adminPsd = adminPsd == null ? null : adminPsd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_admin.admin_name
     *
     * @return the value of user_admin.admin_name
     *
     * @mbg.generated
     */
    public String getAdminName() {
        return adminName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_admin.admin_name
     *
     * @param adminName the value for user_admin.admin_name
     *
     * @mbg.generated
     */
    public void setAdminName(String adminName) {
        this.adminName = adminName == null ? null : adminName.trim();
    }
}