package com.qingxun.pub.generate.pojo;

public class UserMerchant extends UserMerchantKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_merchant.mer_name
     *
     * @mbg.generated
     */
    private String merName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_merchant.mer_info
     *
     * @mbg.generated
     */
    private String merInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_merchant.mer_imgurl
     *
     * @mbg.generated
     */
    private String merImgurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_merchant.mer_sturts
     *
     * @mbg.generated
     */
    private Integer merSturts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_merchant.mer_phone
     *
     * @mbg.generated
     */
    private String merPhone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_merchant.mer_name
     *
     * @return the value of user_merchant.mer_name
     *
     * @mbg.generated
     */
    public String getMerName() {
        return merName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_merchant.mer_name
     *
     * @param merName the value for user_merchant.mer_name
     *
     * @mbg.generated
     */
    public void setMerName(String merName) {
        this.merName = merName == null ? null : merName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_merchant.mer_info
     *
     * @return the value of user_merchant.mer_info
     *
     * @mbg.generated
     */
    public String getMerInfo() {
        return merInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_merchant.mer_info
     *
     * @param merInfo the value for user_merchant.mer_info
     *
     * @mbg.generated
     */
    public void setMerInfo(String merInfo) {
        this.merInfo = merInfo == null ? null : merInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_merchant.mer_imgurl
     *
     * @return the value of user_merchant.mer_imgurl
     *
     * @mbg.generated
     */
    public String getMerImgurl() {
        return merImgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_merchant.mer_imgurl
     *
     * @param merImgurl the value for user_merchant.mer_imgurl
     *
     * @mbg.generated
     */
    public void setMerImgurl(String merImgurl) {
        this.merImgurl = merImgurl == null ? null : merImgurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_merchant.mer_sturts
     *
     * @return the value of user_merchant.mer_sturts
     *
     * @mbg.generated
     */
    public Integer getMerSturts() {
        return merSturts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_merchant.mer_sturts
     *
     * @param merSturts the value for user_merchant.mer_sturts
     *
     * @mbg.generated
     */
    public void setMerSturts(Integer merSturts) {
        this.merSturts = merSturts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_merchant.mer_phone
     *
     * @return the value of user_merchant.mer_phone
     *
     * @mbg.generated
     */
    public String getMerPhone() {
        return merPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_merchant.mer_phone
     *
     * @param merPhone the value for user_merchant.mer_phone
     *
     * @mbg.generated
     */
    public void setMerPhone(String merPhone) {
        this.merPhone = merPhone == null ? null : merPhone.trim();
    }
}