package com.qingxun.pub.generate.pojo;

public class UserMerchantKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_merchant._id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_merchant.mer_id
     *
     * @mbg.generated
     */
    private Integer merId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_merchant._id
     *
     * @return the value of user_merchant._id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_merchant._id
     *
     * @param id the value for user_merchant._id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_merchant.mer_id
     *
     * @return the value of user_merchant.mer_id
     *
     * @mbg.generated
     */
    public Integer getMerId() {
        return merId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_merchant.mer_id
     *
     * @param merId the value for user_merchant.mer_id
     *
     * @mbg.generated
     */
    public void setMerId(Integer merId) {
        this.merId = merId;
    }
}