package com.qingxun.pub.generate.pojo;

public class UserUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_user._id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_user.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_user.admin_id
     *
     * @mbg.generated
     */
    private Integer adminId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_user.merchant_id
     *
     * @mbg.generated
     */
    private Integer merchantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_user.user_imgurl
     *
     * @mbg.generated
     */
    private String userImgurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_user.user_openid
     *
     * @mbg.generated
     */
    private String userOpenid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_user.user_money
     *
     * @mbg.generated
     */
    private Float userMoney;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_user._id
     *
     * @return the value of user_user._id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_user._id
     *
     * @param id the value for user_user._id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_user.user_id
     *
     * @return the value of user_user.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_user.user_id
     *
     * @param userId the value for user_user.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_user.admin_id
     *
     * @return the value of user_user.admin_id
     *
     * @mbg.generated
     */
    public Integer getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_user.admin_id
     *
     * @param adminId the value for user_user.admin_id
     *
     * @mbg.generated
     */
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_user.merchant_id
     *
     * @return the value of user_user.merchant_id
     *
     * @mbg.generated
     */
    public Integer getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_user.merchant_id
     *
     * @param merchantId the value for user_user.merchant_id
     *
     * @mbg.generated
     */
    public void setMerchantId(Integer merchantId) {
        this.merchantId = merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_user.user_imgurl
     *
     * @return the value of user_user.user_imgurl
     *
     * @mbg.generated
     */
    public String getUserImgurl() {
        return userImgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_user.user_imgurl
     *
     * @param userImgurl the value for user_user.user_imgurl
     *
     * @mbg.generated
     */
    public void setUserImgurl(String userImgurl) {
        this.userImgurl = userImgurl == null ? null : userImgurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_user.user_openid
     *
     * @return the value of user_user.user_openid
     *
     * @mbg.generated
     */
    public String getUserOpenid() {
        return userOpenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_user.user_openid
     *
     * @param userOpenid the value for user_user.user_openid
     *
     * @mbg.generated
     */
    public void setUserOpenid(String userOpenid) {
        this.userOpenid = userOpenid == null ? null : userOpenid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_user.user_money
     *
     * @return the value of user_user.user_money
     *
     * @mbg.generated
     */
    public Float getUserMoney() {
        return userMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_user.user_money
     *
     * @param userMoney the value for user_user.user_money
     *
     * @mbg.generated
     */
    public void setUserMoney(Float userMoney) {
        this.userMoney = userMoney;
    }
}