package com.qingxun.pub.generate.pojo;

public class UserUserOthKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_user_oth._id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_user_oth.oth_id
     *
     * @mbg.generated
     */
    private Integer othId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_user_oth._id
     *
     * @return the value of user_user_oth._id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_user_oth._id
     *
     * @param id the value for user_user_oth._id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_user_oth.oth_id
     *
     * @return the value of user_user_oth.oth_id
     *
     * @mbg.generated
     */
    public Integer getOthId() {
        return othId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_user_oth.oth_id
     *
     * @param othId the value for user_user_oth.oth_id
     *
     * @mbg.generated
     */
    public void setOthId(Integer othId) {
        this.othId = othId;
    }
}