package com.qingxun.pub.generate.pojo;

public class UserMerchant extends UserMerchantKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_merchant.mer_name
     *
     * @mbg.generated
     */
    private String merName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_merchant.mar_info
     *
     * @mbg.generated
     */
    private String marInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_merchant.mar_info_imgurl
     *
     * @mbg.generated
     */
    private String marInfoImgurl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_merchant.mer_name
     *
     * @return the value of user_merchant.mer_name
     *
     * @mbg.generated
     */
    public String getMerName() {
        return merName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_merchant.mer_name
     *
     * @param merName the value for user_merchant.mer_name
     *
     * @mbg.generated
     */
    public void setMerName(String merName) {
        this.merName = merName == null ? null : merName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_merchant.mar_info
     *
     * @return the value of user_merchant.mar_info
     *
     * @mbg.generated
     */
    public String getMarInfo() {
        return marInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_merchant.mar_info
     *
     * @param marInfo the value for user_merchant.mar_info
     *
     * @mbg.generated
     */
    public void setMarInfo(String marInfo) {
        this.marInfo = marInfo == null ? null : marInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_merchant.mar_info_imgurl
     *
     * @return the value of user_merchant.mar_info_imgurl
     *
     * @mbg.generated
     */
    public String getMarInfoImgurl() {
        return marInfoImgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_merchant.mar_info_imgurl
     *
     * @param marInfoImgurl the value for user_merchant.mar_info_imgurl
     *
     * @mbg.generated
     */
    public void setMarInfoImgurl(String marInfoImgurl) {
        this.marInfoImgurl = marInfoImgurl == null ? null : marInfoImgurl.trim();
    }
}