package com.qingxun.pub.generate.pojo;

public class UserAdminKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_admin._id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_admin.admin_id
     *
     * @mbg.generated
     */
    private Integer adminId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_admin._id
     *
     * @return the value of user_admin._id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_admin._id
     *
     * @param id the value for user_admin._id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_admin.admin_id
     *
     * @return the value of user_admin.admin_id
     *
     * @mbg.generated
     */
    public Integer getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_admin.admin_id
     *
     * @param adminId the value for user_admin.admin_id
     *
     * @mbg.generated
     */
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }
}