package com.qingxun.pub.generate.pojo;

import java.util.ArrayList;
import java.util.List;

public class UserUserOthExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_user_oth
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_user_oth
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_user_oth
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_user_oth
     *
     * @mbg.generated
     */
    public UserUserOthExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_user_oth
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_user_oth
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_user_oth
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_user_oth
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_user_oth
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_user_oth
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_user_oth
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_user_oth
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_user_oth
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_user_oth
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_user_oth
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("_id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("_id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("_id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("_id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("_id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("_id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("_id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("_id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("_id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("_id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("_id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("_id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andOthIdIsNull() {
            addCriterion("oth_id is null");
            return (Criteria) this;
        }

        public Criteria andOthIdIsNotNull() {
            addCriterion("oth_id is not null");
            return (Criteria) this;
        }

        public Criteria andOthIdEqualTo(Integer value) {
            addCriterion("oth_id =", value, "othId");
            return (Criteria) this;
        }

        public Criteria andOthIdNotEqualTo(Integer value) {
            addCriterion("oth_id <>", value, "othId");
            return (Criteria) this;
        }

        public Criteria andOthIdGreaterThan(Integer value) {
            addCriterion("oth_id >", value, "othId");
            return (Criteria) this;
        }

        public Criteria andOthIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("oth_id >=", value, "othId");
            return (Criteria) this;
        }

        public Criteria andOthIdLessThan(Integer value) {
            addCriterion("oth_id <", value, "othId");
            return (Criteria) this;
        }

        public Criteria andOthIdLessThanOrEqualTo(Integer value) {
            addCriterion("oth_id <=", value, "othId");
            return (Criteria) this;
        }

        public Criteria andOthIdIn(List<Integer> values) {
            addCriterion("oth_id in", values, "othId");
            return (Criteria) this;
        }

        public Criteria andOthIdNotIn(List<Integer> values) {
            addCriterion("oth_id not in", values, "othId");
            return (Criteria) this;
        }

        public Criteria andOthIdBetween(Integer value1, Integer value2) {
            addCriterion("oth_id between", value1, value2, "othId");
            return (Criteria) this;
        }

        public Criteria andOthIdNotBetween(Integer value1, Integer value2) {
            addCriterion("oth_id not between", value1, value2, "othId");
            return (Criteria) this;
        }

        public Criteria andOthPhoneIsNull() {
            addCriterion("oth_phone is null");
            return (Criteria) this;
        }

        public Criteria andOthPhoneIsNotNull() {
            addCriterion("oth_phone is not null");
            return (Criteria) this;
        }

        public Criteria andOthPhoneEqualTo(String value) {
            addCriterion("oth_phone =", value, "othPhone");
            return (Criteria) this;
        }

        public Criteria andOthPhoneNotEqualTo(String value) {
            addCriterion("oth_phone <>", value, "othPhone");
            return (Criteria) this;
        }

        public Criteria andOthPhoneGreaterThan(String value) {
            addCriterion("oth_phone >", value, "othPhone");
            return (Criteria) this;
        }

        public Criteria andOthPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("oth_phone >=", value, "othPhone");
            return (Criteria) this;
        }

        public Criteria andOthPhoneLessThan(String value) {
            addCriterion("oth_phone <", value, "othPhone");
            return (Criteria) this;
        }

        public Criteria andOthPhoneLessThanOrEqualTo(String value) {
            addCriterion("oth_phone <=", value, "othPhone");
            return (Criteria) this;
        }

        public Criteria andOthPhoneLike(String value) {
            addCriterion("oth_phone like", value, "othPhone");
            return (Criteria) this;
        }

        public Criteria andOthPhoneNotLike(String value) {
            addCriterion("oth_phone not like", value, "othPhone");
            return (Criteria) this;
        }

        public Criteria andOthPhoneIn(List<String> values) {
            addCriterion("oth_phone in", values, "othPhone");
            return (Criteria) this;
        }

        public Criteria andOthPhoneNotIn(List<String> values) {
            addCriterion("oth_phone not in", values, "othPhone");
            return (Criteria) this;
        }

        public Criteria andOthPhoneBetween(String value1, String value2) {
            addCriterion("oth_phone between", value1, value2, "othPhone");
            return (Criteria) this;
        }

        public Criteria andOthPhoneNotBetween(String value1, String value2) {
            addCriterion("oth_phone not between", value1, value2, "othPhone");
            return (Criteria) this;
        }

        public Criteria andOthSuueIsNull() {
            addCriterion("oth_suue is null");
            return (Criteria) this;
        }

        public Criteria andOthSuueIsNotNull() {
            addCriterion("oth_suue is not null");
            return (Criteria) this;
        }

        public Criteria andOthSuueEqualTo(String value) {
            addCriterion("oth_suue =", value, "othSuue");
            return (Criteria) this;
        }

        public Criteria andOthSuueNotEqualTo(String value) {
            addCriterion("oth_suue <>", value, "othSuue");
            return (Criteria) this;
        }

        public Criteria andOthSuueGreaterThan(String value) {
            addCriterion("oth_suue >", value, "othSuue");
            return (Criteria) this;
        }

        public Criteria andOthSuueGreaterThanOrEqualTo(String value) {
            addCriterion("oth_suue >=", value, "othSuue");
            return (Criteria) this;
        }

        public Criteria andOthSuueLessThan(String value) {
            addCriterion("oth_suue <", value, "othSuue");
            return (Criteria) this;
        }

        public Criteria andOthSuueLessThanOrEqualTo(String value) {
            addCriterion("oth_suue <=", value, "othSuue");
            return (Criteria) this;
        }

        public Criteria andOthSuueLike(String value) {
            addCriterion("oth_suue like", value, "othSuue");
            return (Criteria) this;
        }

        public Criteria andOthSuueNotLike(String value) {
            addCriterion("oth_suue not like", value, "othSuue");
            return (Criteria) this;
        }

        public Criteria andOthSuueIn(List<String> values) {
            addCriterion("oth_suue in", values, "othSuue");
            return (Criteria) this;
        }

        public Criteria andOthSuueNotIn(List<String> values) {
            addCriterion("oth_suue not in", values, "othSuue");
            return (Criteria) this;
        }

        public Criteria andOthSuueBetween(String value1, String value2) {
            addCriterion("oth_suue between", value1, value2, "othSuue");
            return (Criteria) this;
        }

        public Criteria andOthSuueNotBetween(String value1, String value2) {
            addCriterion("oth_suue not between", value1, value2, "othSuue");
            return (Criteria) this;
        }

        public Criteria andOthSchoolIsNull() {
            addCriterion("oth_school is null");
            return (Criteria) this;
        }

        public Criteria andOthSchoolIsNotNull() {
            addCriterion("oth_school is not null");
            return (Criteria) this;
        }

        public Criteria andOthSchoolEqualTo(String value) {
            addCriterion("oth_school =", value, "othSchool");
            return (Criteria) this;
        }

        public Criteria andOthSchoolNotEqualTo(String value) {
            addCriterion("oth_school <>", value, "othSchool");
            return (Criteria) this;
        }

        public Criteria andOthSchoolGreaterThan(String value) {
            addCriterion("oth_school >", value, "othSchool");
            return (Criteria) this;
        }

        public Criteria andOthSchoolGreaterThanOrEqualTo(String value) {
            addCriterion("oth_school >=", value, "othSchool");
            return (Criteria) this;
        }

        public Criteria andOthSchoolLessThan(String value) {
            addCriterion("oth_school <", value, "othSchool");
            return (Criteria) this;
        }

        public Criteria andOthSchoolLessThanOrEqualTo(String value) {
            addCriterion("oth_school <=", value, "othSchool");
            return (Criteria) this;
        }

        public Criteria andOthSchoolLike(String value) {
            addCriterion("oth_school like", value, "othSchool");
            return (Criteria) this;
        }

        public Criteria andOthSchoolNotLike(String value) {
            addCriterion("oth_school not like", value, "othSchool");
            return (Criteria) this;
        }

        public Criteria andOthSchoolIn(List<String> values) {
            addCriterion("oth_school in", values, "othSchool");
            return (Criteria) this;
        }

        public Criteria andOthSchoolNotIn(List<String> values) {
            addCriterion("oth_school not in", values, "othSchool");
            return (Criteria) this;
        }

        public Criteria andOthSchoolBetween(String value1, String value2) {
            addCriterion("oth_school between", value1, value2, "othSchool");
            return (Criteria) this;
        }

        public Criteria andOthSchoolNotBetween(String value1, String value2) {
            addCriterion("oth_school not between", value1, value2, "othSchool");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_user_oth
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_user_oth
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}