package com.qingxun.pub.generate.pojo;

import java.util.ArrayList;
import java.util.List;

public class ViewMisAllExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table view_mis_all
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table view_mis_all
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table view_mis_all
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_mis_all
     *
     * @mbg.generated
     */
    public ViewMisAllExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_mis_all
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_mis_all
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_mis_all
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_mis_all
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_mis_all
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_mis_all
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_mis_all
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_mis_all
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_mis_all
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_mis_all
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table view_mis_all
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUserImgurlIsNull() {
            addCriterion("user_imgurl is null");
            return (Criteria) this;
        }

        public Criteria andUserImgurlIsNotNull() {
            addCriterion("user_imgurl is not null");
            return (Criteria) this;
        }

        public Criteria andUserImgurlEqualTo(String value) {
            addCriterion("user_imgurl =", value, "userImgurl");
            return (Criteria) this;
        }

        public Criteria andUserImgurlNotEqualTo(String value) {
            addCriterion("user_imgurl <>", value, "userImgurl");
            return (Criteria) this;
        }

        public Criteria andUserImgurlGreaterThan(String value) {
            addCriterion("user_imgurl >", value, "userImgurl");
            return (Criteria) this;
        }

        public Criteria andUserImgurlGreaterThanOrEqualTo(String value) {
            addCriterion("user_imgurl >=", value, "userImgurl");
            return (Criteria) this;
        }

        public Criteria andUserImgurlLessThan(String value) {
            addCriterion("user_imgurl <", value, "userImgurl");
            return (Criteria) this;
        }

        public Criteria andUserImgurlLessThanOrEqualTo(String value) {
            addCriterion("user_imgurl <=", value, "userImgurl");
            return (Criteria) this;
        }

        public Criteria andUserImgurlLike(String value) {
            addCriterion("user_imgurl like", value, "userImgurl");
            return (Criteria) this;
        }

        public Criteria andUserImgurlNotLike(String value) {
            addCriterion("user_imgurl not like", value, "userImgurl");
            return (Criteria) this;
        }

        public Criteria andUserImgurlIn(List<String> values) {
            addCriterion("user_imgurl in", values, "userImgurl");
            return (Criteria) this;
        }

        public Criteria andUserImgurlNotIn(List<String> values) {
            addCriterion("user_imgurl not in", values, "userImgurl");
            return (Criteria) this;
        }

        public Criteria andUserImgurlBetween(String value1, String value2) {
            addCriterion("user_imgurl between", value1, value2, "userImgurl");
            return (Criteria) this;
        }

        public Criteria andUserImgurlNotBetween(String value1, String value2) {
            addCriterion("user_imgurl not between", value1, value2, "userImgurl");
            return (Criteria) this;
        }

        public Criteria andFaqiIdIsNull() {
            addCriterion("faqi_id is null");
            return (Criteria) this;
        }

        public Criteria andFaqiIdIsNotNull() {
            addCriterion("faqi_id is not null");
            return (Criteria) this;
        }

        public Criteria andFaqiIdEqualTo(Integer value) {
            addCriterion("faqi_id =", value, "faqiId");
            return (Criteria) this;
        }

        public Criteria andFaqiIdNotEqualTo(Integer value) {
            addCriterion("faqi_id <>", value, "faqiId");
            return (Criteria) this;
        }

        public Criteria andFaqiIdGreaterThan(Integer value) {
            addCriterion("faqi_id >", value, "faqiId");
            return (Criteria) this;
        }

        public Criteria andFaqiIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("faqi_id >=", value, "faqiId");
            return (Criteria) this;
        }

        public Criteria andFaqiIdLessThan(Integer value) {
            addCriterion("faqi_id <", value, "faqiId");
            return (Criteria) this;
        }

        public Criteria andFaqiIdLessThanOrEqualTo(Integer value) {
            addCriterion("faqi_id <=", value, "faqiId");
            return (Criteria) this;
        }

        public Criteria andFaqiIdIn(List<Integer> values) {
            addCriterion("faqi_id in", values, "faqiId");
            return (Criteria) this;
        }

        public Criteria andFaqiIdNotIn(List<Integer> values) {
            addCriterion("faqi_id not in", values, "faqiId");
            return (Criteria) this;
        }

        public Criteria andFaqiIdBetween(Integer value1, Integer value2) {
            addCriterion("faqi_id between", value1, value2, "faqiId");
            return (Criteria) this;
        }

        public Criteria andFaqiIdNotBetween(Integer value1, Integer value2) {
            addCriterion("faqi_id not between", value1, value2, "faqiId");
            return (Criteria) this;
        }

        public Criteria andMisContentIsNull() {
            addCriterion("mis_content is null");
            return (Criteria) this;
        }

        public Criteria andMisContentIsNotNull() {
            addCriterion("mis_content is not null");
            return (Criteria) this;
        }

        public Criteria andMisContentEqualTo(String value) {
            addCriterion("mis_content =", value, "misContent");
            return (Criteria) this;
        }

        public Criteria andMisContentNotEqualTo(String value) {
            addCriterion("mis_content <>", value, "misContent");
            return (Criteria) this;
        }

        public Criteria andMisContentGreaterThan(String value) {
            addCriterion("mis_content >", value, "misContent");
            return (Criteria) this;
        }

        public Criteria andMisContentGreaterThanOrEqualTo(String value) {
            addCriterion("mis_content >=", value, "misContent");
            return (Criteria) this;
        }

        public Criteria andMisContentLessThan(String value) {
            addCriterion("mis_content <", value, "misContent");
            return (Criteria) this;
        }

        public Criteria andMisContentLessThanOrEqualTo(String value) {
            addCriterion("mis_content <=", value, "misContent");
            return (Criteria) this;
        }

        public Criteria andMisContentLike(String value) {
            addCriterion("mis_content like", value, "misContent");
            return (Criteria) this;
        }

        public Criteria andMisContentNotLike(String value) {
            addCriterion("mis_content not like", value, "misContent");
            return (Criteria) this;
        }

        public Criteria andMisContentIn(List<String> values) {
            addCriterion("mis_content in", values, "misContent");
            return (Criteria) this;
        }

        public Criteria andMisContentNotIn(List<String> values) {
            addCriterion("mis_content not in", values, "misContent");
            return (Criteria) this;
        }

        public Criteria andMisContentBetween(String value1, String value2) {
            addCriterion("mis_content between", value1, value2, "misContent");
            return (Criteria) this;
        }

        public Criteria andMisContentNotBetween(String value1, String value2) {
            addCriterion("mis_content not between", value1, value2, "misContent");
            return (Criteria) this;
        }

        public Criteria andMisTime1IsNull() {
            addCriterion("mis_time1 is null");
            return (Criteria) this;
        }

        public Criteria andMisTime1IsNotNull() {
            addCriterion("mis_time1 is not null");
            return (Criteria) this;
        }

        public Criteria andMisTime1EqualTo(String value) {
            addCriterion("mis_time1 =", value, "misTime1");
            return (Criteria) this;
        }

        public Criteria andMisTime1NotEqualTo(String value) {
            addCriterion("mis_time1 <>", value, "misTime1");
            return (Criteria) this;
        }

        public Criteria andMisTime1GreaterThan(String value) {
            addCriterion("mis_time1 >", value, "misTime1");
            return (Criteria) this;
        }

        public Criteria andMisTime1GreaterThanOrEqualTo(String value) {
            addCriterion("mis_time1 >=", value, "misTime1");
            return (Criteria) this;
        }

        public Criteria andMisTime1LessThan(String value) {
            addCriterion("mis_time1 <", value, "misTime1");
            return (Criteria) this;
        }

        public Criteria andMisTime1LessThanOrEqualTo(String value) {
            addCriterion("mis_time1 <=", value, "misTime1");
            return (Criteria) this;
        }

        public Criteria andMisTime1Like(String value) {
            addCriterion("mis_time1 like", value, "misTime1");
            return (Criteria) this;
        }

        public Criteria andMisTime1NotLike(String value) {
            addCriterion("mis_time1 not like", value, "misTime1");
            return (Criteria) this;
        }

        public Criteria andMisTime1In(List<String> values) {
            addCriterion("mis_time1 in", values, "misTime1");
            return (Criteria) this;
        }

        public Criteria andMisTime1NotIn(List<String> values) {
            addCriterion("mis_time1 not in", values, "misTime1");
            return (Criteria) this;
        }

        public Criteria andMisTime1Between(String value1, String value2) {
            addCriterion("mis_time1 between", value1, value2, "misTime1");
            return (Criteria) this;
        }

        public Criteria andMisTime1NotBetween(String value1, String value2) {
            addCriterion("mis_time1 not between", value1, value2, "misTime1");
            return (Criteria) this;
        }

        public Criteria andMisTime2IsNull() {
            addCriterion("mis_time2 is null");
            return (Criteria) this;
        }

        public Criteria andMisTime2IsNotNull() {
            addCriterion("mis_time2 is not null");
            return (Criteria) this;
        }

        public Criteria andMisTime2EqualTo(String value) {
            addCriterion("mis_time2 =", value, "misTime2");
            return (Criteria) this;
        }

        public Criteria andMisTime2NotEqualTo(String value) {
            addCriterion("mis_time2 <>", value, "misTime2");
            return (Criteria) this;
        }

        public Criteria andMisTime2GreaterThan(String value) {
            addCriterion("mis_time2 >", value, "misTime2");
            return (Criteria) this;
        }

        public Criteria andMisTime2GreaterThanOrEqualTo(String value) {
            addCriterion("mis_time2 >=", value, "misTime2");
            return (Criteria) this;
        }

        public Criteria andMisTime2LessThan(String value) {
            addCriterion("mis_time2 <", value, "misTime2");
            return (Criteria) this;
        }

        public Criteria andMisTime2LessThanOrEqualTo(String value) {
            addCriterion("mis_time2 <=", value, "misTime2");
            return (Criteria) this;
        }

        public Criteria andMisTime2Like(String value) {
            addCriterion("mis_time2 like", value, "misTime2");
            return (Criteria) this;
        }

        public Criteria andMisTime2NotLike(String value) {
            addCriterion("mis_time2 not like", value, "misTime2");
            return (Criteria) this;
        }

        public Criteria andMisTime2In(List<String> values) {
            addCriterion("mis_time2 in", values, "misTime2");
            return (Criteria) this;
        }

        public Criteria andMisTime2NotIn(List<String> values) {
            addCriterion("mis_time2 not in", values, "misTime2");
            return (Criteria) this;
        }

        public Criteria andMisTime2Between(String value1, String value2) {
            addCriterion("mis_time2 between", value1, value2, "misTime2");
            return (Criteria) this;
        }

        public Criteria andMisTime2NotBetween(String value1, String value2) {
            addCriterion("mis_time2 not between", value1, value2, "misTime2");
            return (Criteria) this;
        }

        public Criteria andMisStrutsIsNull() {
            addCriterion("mis_struts is null");
            return (Criteria) this;
        }

        public Criteria andMisStrutsIsNotNull() {
            addCriterion("mis_struts is not null");
            return (Criteria) this;
        }

        public Criteria andMisStrutsEqualTo(Integer value) {
            addCriterion("mis_struts =", value, "misStruts");
            return (Criteria) this;
        }

        public Criteria andMisStrutsNotEqualTo(Integer value) {
            addCriterion("mis_struts <>", value, "misStruts");
            return (Criteria) this;
        }

        public Criteria andMisStrutsGreaterThan(Integer value) {
            addCriterion("mis_struts >", value, "misStruts");
            return (Criteria) this;
        }

        public Criteria andMisStrutsGreaterThanOrEqualTo(Integer value) {
            addCriterion("mis_struts >=", value, "misStruts");
            return (Criteria) this;
        }

        public Criteria andMisStrutsLessThan(Integer value) {
            addCriterion("mis_struts <", value, "misStruts");
            return (Criteria) this;
        }

        public Criteria andMisStrutsLessThanOrEqualTo(Integer value) {
            addCriterion("mis_struts <=", value, "misStruts");
            return (Criteria) this;
        }

        public Criteria andMisStrutsIn(List<Integer> values) {
            addCriterion("mis_struts in", values, "misStruts");
            return (Criteria) this;
        }

        public Criteria andMisStrutsNotIn(List<Integer> values) {
            addCriterion("mis_struts not in", values, "misStruts");
            return (Criteria) this;
        }

        public Criteria andMisStrutsBetween(Integer value1, Integer value2) {
            addCriterion("mis_struts between", value1, value2, "misStruts");
            return (Criteria) this;
        }

        public Criteria andMisStrutsNotBetween(Integer value1, Integer value2) {
            addCriterion("mis_struts not between", value1, value2, "misStruts");
            return (Criteria) this;
        }

        public Criteria andMisXuqqnumIsNull() {
            addCriterion("mis_xuqqnum is null");
            return (Criteria) this;
        }

        public Criteria andMisXuqqnumIsNotNull() {
            addCriterion("mis_xuqqnum is not null");
            return (Criteria) this;
        }

        public Criteria andMisXuqqnumEqualTo(Integer value) {
            addCriterion("mis_xuqqnum =", value, "misXuqqnum");
            return (Criteria) this;
        }

        public Criteria andMisXuqqnumNotEqualTo(Integer value) {
            addCriterion("mis_xuqqnum <>", value, "misXuqqnum");
            return (Criteria) this;
        }

        public Criteria andMisXuqqnumGreaterThan(Integer value) {
            addCriterion("mis_xuqqnum >", value, "misXuqqnum");
            return (Criteria) this;
        }

        public Criteria andMisXuqqnumGreaterThanOrEqualTo(Integer value) {
            addCriterion("mis_xuqqnum >=", value, "misXuqqnum");
            return (Criteria) this;
        }

        public Criteria andMisXuqqnumLessThan(Integer value) {
            addCriterion("mis_xuqqnum <", value, "misXuqqnum");
            return (Criteria) this;
        }

        public Criteria andMisXuqqnumLessThanOrEqualTo(Integer value) {
            addCriterion("mis_xuqqnum <=", value, "misXuqqnum");
            return (Criteria) this;
        }

        public Criteria andMisXuqqnumIn(List<Integer> values) {
            addCriterion("mis_xuqqnum in", values, "misXuqqnum");
            return (Criteria) this;
        }

        public Criteria andMisXuqqnumNotIn(List<Integer> values) {
            addCriterion("mis_xuqqnum not in", values, "misXuqqnum");
            return (Criteria) this;
        }

        public Criteria andMisXuqqnumBetween(Integer value1, Integer value2) {
            addCriterion("mis_xuqqnum between", value1, value2, "misXuqqnum");
            return (Criteria) this;
        }

        public Criteria andMisXuqqnumNotBetween(Integer value1, Integer value2) {
            addCriterion("mis_xuqqnum not between", value1, value2, "misXuqqnum");
            return (Criteria) this;
        }

        public Criteria andMisMoneyIsNull() {
            addCriterion("mis_money is null");
            return (Criteria) this;
        }

        public Criteria andMisMoneyIsNotNull() {
            addCriterion("mis_money is not null");
            return (Criteria) this;
        }

        public Criteria andMisMoneyEqualTo(Float value) {
            addCriterion("mis_money =", value, "misMoney");
            return (Criteria) this;
        }

        public Criteria andMisMoneyNotEqualTo(Float value) {
            addCriterion("mis_money <>", value, "misMoney");
            return (Criteria) this;
        }

        public Criteria andMisMoneyGreaterThan(Float value) {
            addCriterion("mis_money >", value, "misMoney");
            return (Criteria) this;
        }

        public Criteria andMisMoneyGreaterThanOrEqualTo(Float value) {
            addCriterion("mis_money >=", value, "misMoney");
            return (Criteria) this;
        }

        public Criteria andMisMoneyLessThan(Float value) {
            addCriterion("mis_money <", value, "misMoney");
            return (Criteria) this;
        }

        public Criteria andMisMoneyLessThanOrEqualTo(Float value) {
            addCriterion("mis_money <=", value, "misMoney");
            return (Criteria) this;
        }

        public Criteria andMisMoneyIn(List<Float> values) {
            addCriterion("mis_money in", values, "misMoney");
            return (Criteria) this;
        }

        public Criteria andMisMoneyNotIn(List<Float> values) {
            addCriterion("mis_money not in", values, "misMoney");
            return (Criteria) this;
        }

        public Criteria andMisMoneyBetween(Float value1, Float value2) {
            addCriterion("mis_money between", value1, value2, "misMoney");
            return (Criteria) this;
        }

        public Criteria andMisMoneyNotBetween(Float value1, Float value2) {
            addCriterion("mis_money not between", value1, value2, "misMoney");
            return (Criteria) this;
        }

        public Criteria andMisTilteIsNull() {
            addCriterion("mis_tilte is null");
            return (Criteria) this;
        }

        public Criteria andMisTilteIsNotNull() {
            addCriterion("mis_tilte is not null");
            return (Criteria) this;
        }

        public Criteria andMisTilteEqualTo(String value) {
            addCriterion("mis_tilte =", value, "misTilte");
            return (Criteria) this;
        }

        public Criteria andMisTilteNotEqualTo(String value) {
            addCriterion("mis_tilte <>", value, "misTilte");
            return (Criteria) this;
        }

        public Criteria andMisTilteGreaterThan(String value) {
            addCriterion("mis_tilte >", value, "misTilte");
            return (Criteria) this;
        }

        public Criteria andMisTilteGreaterThanOrEqualTo(String value) {
            addCriterion("mis_tilte >=", value, "misTilte");
            return (Criteria) this;
        }

        public Criteria andMisTilteLessThan(String value) {
            addCriterion("mis_tilte <", value, "misTilte");
            return (Criteria) this;
        }

        public Criteria andMisTilteLessThanOrEqualTo(String value) {
            addCriterion("mis_tilte <=", value, "misTilte");
            return (Criteria) this;
        }

        public Criteria andMisTilteLike(String value) {
            addCriterion("mis_tilte like", value, "misTilte");
            return (Criteria) this;
        }

        public Criteria andMisTilteNotLike(String value) {
            addCriterion("mis_tilte not like", value, "misTilte");
            return (Criteria) this;
        }

        public Criteria andMisTilteIn(List<String> values) {
            addCriterion("mis_tilte in", values, "misTilte");
            return (Criteria) this;
        }

        public Criteria andMisTilteNotIn(List<String> values) {
            addCriterion("mis_tilte not in", values, "misTilte");
            return (Criteria) this;
        }

        public Criteria andMisTilteBetween(String value1, String value2) {
            addCriterion("mis_tilte between", value1, value2, "misTilte");
            return (Criteria) this;
        }

        public Criteria andMisTilteNotBetween(String value1, String value2) {
            addCriterion("mis_tilte not between", value1, value2, "misTilte");
            return (Criteria) this;
        }

        public Criteria andMisTopIsNull() {
            addCriterion("mis_top is null");
            return (Criteria) this;
        }

        public Criteria andMisTopIsNotNull() {
            addCriterion("mis_top is not null");
            return (Criteria) this;
        }

        public Criteria andMisTopEqualTo(Integer value) {
            addCriterion("mis_top =", value, "misTop");
            return (Criteria) this;
        }

        public Criteria andMisTopNotEqualTo(Integer value) {
            addCriterion("mis_top <>", value, "misTop");
            return (Criteria) this;
        }

        public Criteria andMisTopGreaterThan(Integer value) {
            addCriterion("mis_top >", value, "misTop");
            return (Criteria) this;
        }

        public Criteria andMisTopGreaterThanOrEqualTo(Integer value) {
            addCriterion("mis_top >=", value, "misTop");
            return (Criteria) this;
        }

        public Criteria andMisTopLessThan(Integer value) {
            addCriterion("mis_top <", value, "misTop");
            return (Criteria) this;
        }

        public Criteria andMisTopLessThanOrEqualTo(Integer value) {
            addCriterion("mis_top <=", value, "misTop");
            return (Criteria) this;
        }

        public Criteria andMisTopIn(List<Integer> values) {
            addCriterion("mis_top in", values, "misTop");
            return (Criteria) this;
        }

        public Criteria andMisTopNotIn(List<Integer> values) {
            addCriterion("mis_top not in", values, "misTop");
            return (Criteria) this;
        }

        public Criteria andMisTopBetween(Integer value1, Integer value2) {
            addCriterion("mis_top between", value1, value2, "misTop");
            return (Criteria) this;
        }

        public Criteria andMisTopNotBetween(Integer value1, Integer value2) {
            addCriterion("mis_top not between", value1, value2, "misTop");
            return (Criteria) this;
        }

        public Criteria andMisIdIsNull() {
            addCriterion("mis_id is null");
            return (Criteria) this;
        }

        public Criteria andMisIdIsNotNull() {
            addCriterion("mis_id is not null");
            return (Criteria) this;
        }

        public Criteria andMisIdEqualTo(Integer value) {
            addCriterion("mis_id =", value, "misId");
            return (Criteria) this;
        }

        public Criteria andMisIdNotEqualTo(Integer value) {
            addCriterion("mis_id <>", value, "misId");
            return (Criteria) this;
        }

        public Criteria andMisIdGreaterThan(Integer value) {
            addCriterion("mis_id >", value, "misId");
            return (Criteria) this;
        }

        public Criteria andMisIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("mis_id >=", value, "misId");
            return (Criteria) this;
        }

        public Criteria andMisIdLessThan(Integer value) {
            addCriterion("mis_id <", value, "misId");
            return (Criteria) this;
        }

        public Criteria andMisIdLessThanOrEqualTo(Integer value) {
            addCriterion("mis_id <=", value, "misId");
            return (Criteria) this;
        }

        public Criteria andMisIdIn(List<Integer> values) {
            addCriterion("mis_id in", values, "misId");
            return (Criteria) this;
        }

        public Criteria andMisIdNotIn(List<Integer> values) {
            addCriterion("mis_id not in", values, "misId");
            return (Criteria) this;
        }

        public Criteria andMisIdBetween(Integer value1, Integer value2) {
            addCriterion("mis_id between", value1, value2, "misId");
            return (Criteria) this;
        }

        public Criteria andMisIdNotBetween(Integer value1, Integer value2) {
            addCriterion("mis_id not between", value1, value2, "misId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table view_mis_all
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table view_mis_all
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}