package com.qingxun.pub.generate.pojo;

public class ViewMisAll {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_mis_all.user_imgurl
     *
     * @mbg.generated
     */
    private String userImgurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_mis_all.faqi_id
     *
     * @mbg.generated
     */
    private Integer faqiId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_mis_all.mis_content
     *
     * @mbg.generated
     */
    private String misContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_mis_all.mis_time1
     *
     * @mbg.generated
     */
    private String misTime1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_mis_all.mis_time2
     *
     * @mbg.generated
     */
    private String misTime2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_mis_all.mis_struts
     *
     * @mbg.generated
     */
    private Integer misStruts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_mis_all.mis_xuqqnum
     *
     * @mbg.generated
     */
    private Integer misXuqqnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_mis_all.mis_money
     *
     * @mbg.generated
     */
    private Float misMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_mis_all.mis_tilte
     *
     * @mbg.generated
     */
    private String misTilte;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_mis_all.mis_top
     *
     * @mbg.generated
     */
    private Integer misTop;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_mis_all.mis_id
     *
     * @mbg.generated
     */
    private Integer misId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_mis_all.user_imgurl
     *
     * @return the value of view_mis_all.user_imgurl
     *
     * @mbg.generated
     */
    public String getUserImgurl() {
        return userImgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_mis_all.user_imgurl
     *
     * @param userImgurl the value for view_mis_all.user_imgurl
     *
     * @mbg.generated
     */
    public void setUserImgurl(String userImgurl) {
        this.userImgurl = userImgurl == null ? null : userImgurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_mis_all.faqi_id
     *
     * @return the value of view_mis_all.faqi_id
     *
     * @mbg.generated
     */
    public Integer getFaqiId() {
        return faqiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_mis_all.faqi_id
     *
     * @param faqiId the value for view_mis_all.faqi_id
     *
     * @mbg.generated
     */
    public void setFaqiId(Integer faqiId) {
        this.faqiId = faqiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_mis_all.mis_content
     *
     * @return the value of view_mis_all.mis_content
     *
     * @mbg.generated
     */
    public String getMisContent() {
        return misContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_mis_all.mis_content
     *
     * @param misContent the value for view_mis_all.mis_content
     *
     * @mbg.generated
     */
    public void setMisContent(String misContent) {
        this.misContent = misContent == null ? null : misContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_mis_all.mis_time1
     *
     * @return the value of view_mis_all.mis_time1
     *
     * @mbg.generated
     */
    public String getMisTime1() {
        return misTime1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_mis_all.mis_time1
     *
     * @param misTime1 the value for view_mis_all.mis_time1
     *
     * @mbg.generated
     */
    public void setMisTime1(String misTime1) {
        this.misTime1 = misTime1 == null ? null : misTime1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_mis_all.mis_time2
     *
     * @return the value of view_mis_all.mis_time2
     *
     * @mbg.generated
     */
    public String getMisTime2() {
        return misTime2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_mis_all.mis_time2
     *
     * @param misTime2 the value for view_mis_all.mis_time2
     *
     * @mbg.generated
     */
    public void setMisTime2(String misTime2) {
        this.misTime2 = misTime2 == null ? null : misTime2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_mis_all.mis_struts
     *
     * @return the value of view_mis_all.mis_struts
     *
     * @mbg.generated
     */
    public Integer getMisStruts() {
        return misStruts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_mis_all.mis_struts
     *
     * @param misStruts the value for view_mis_all.mis_struts
     *
     * @mbg.generated
     */
    public void setMisStruts(Integer misStruts) {
        this.misStruts = misStruts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_mis_all.mis_xuqqnum
     *
     * @return the value of view_mis_all.mis_xuqqnum
     *
     * @mbg.generated
     */
    public Integer getMisXuqqnum() {
        return misXuqqnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_mis_all.mis_xuqqnum
     *
     * @param misXuqqnum the value for view_mis_all.mis_xuqqnum
     *
     * @mbg.generated
     */
    public void setMisXuqqnum(Integer misXuqqnum) {
        this.misXuqqnum = misXuqqnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_mis_all.mis_money
     *
     * @return the value of view_mis_all.mis_money
     *
     * @mbg.generated
     */
    public Float getMisMoney() {
        return misMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_mis_all.mis_money
     *
     * @param misMoney the value for view_mis_all.mis_money
     *
     * @mbg.generated
     */
    public void setMisMoney(Float misMoney) {
        this.misMoney = misMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_mis_all.mis_tilte
     *
     * @return the value of view_mis_all.mis_tilte
     *
     * @mbg.generated
     */
    public String getMisTilte() {
        return misTilte;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_mis_all.mis_tilte
     *
     * @param misTilte the value for view_mis_all.mis_tilte
     *
     * @mbg.generated
     */
    public void setMisTilte(String misTilte) {
        this.misTilte = misTilte == null ? null : misTilte.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_mis_all.mis_top
     *
     * @return the value of view_mis_all.mis_top
     *
     * @mbg.generated
     */
    public Integer getMisTop() {
        return misTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_mis_all.mis_top
     *
     * @param misTop the value for view_mis_all.mis_top
     *
     * @mbg.generated
     */
    public void setMisTop(Integer misTop) {
        this.misTop = misTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_mis_all.mis_id
     *
     * @return the value of view_mis_all.mis_id
     *
     * @mbg.generated
     */
    public Integer getMisId() {
        return misId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_mis_all.mis_id
     *
     * @param misId the value for view_mis_all.mis_id
     *
     * @mbg.generated
     */
    public void setMisId(Integer misId) {
        this.misId = misId;
    }
}