package com.qingxun.pub.generate.pojo;

public class ViewMisJpuzUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_mis_jpuz_user.jpuz_id
     *
     * @mbg.generated
     */
    private Integer jpuzId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_mis_jpuz_user.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_mis_jpuz_user.jpuz_time
     *
     * @mbg.generated
     */
    private String jpuzTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_mis_jpuz_user.jpuz_sturts
     *
     * @mbg.generated
     */
    private String jpuzSturts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_mis_jpuz_user.mis_tilte
     *
     * @mbg.generated
     */
    private String misTilte;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_mis_jpuz_user.mis_content
     *
     * @mbg.generated
     */
    private String misContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_mis_jpuz_user.mis_time1
     *
     * @mbg.generated
     */
    private String misTime1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_mis_jpuz_user.mis_time2
     *
     * @mbg.generated
     */
    private String misTime2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_mis_jpuz_user.mis_struts
     *
     * @mbg.generated
     */
    private Integer misStruts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_mis_jpuz_user.mis_xuqqnum
     *
     * @mbg.generated
     */
    private Integer misXuqqnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_mis_jpuz_user.mis_money
     *
     * @mbg.generated
     */
    private Float misMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_mis_jpuz_user.user_imgurl
     *
     * @mbg.generated
     */
    private String userImgurl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_mis_jpuz_user.jpuz_id
     *
     * @return the value of view_mis_jpuz_user.jpuz_id
     *
     * @mbg.generated
     */
    public Integer getJpuzId() {
        return jpuzId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_mis_jpuz_user.jpuz_id
     *
     * @param jpuzId the value for view_mis_jpuz_user.jpuz_id
     *
     * @mbg.generated
     */
    public void setJpuzId(Integer jpuzId) {
        this.jpuzId = jpuzId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_mis_jpuz_user.user_id
     *
     * @return the value of view_mis_jpuz_user.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_mis_jpuz_user.user_id
     *
     * @param userId the value for view_mis_jpuz_user.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_mis_jpuz_user.jpuz_time
     *
     * @return the value of view_mis_jpuz_user.jpuz_time
     *
     * @mbg.generated
     */
    public String getJpuzTime() {
        return jpuzTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_mis_jpuz_user.jpuz_time
     *
     * @param jpuzTime the value for view_mis_jpuz_user.jpuz_time
     *
     * @mbg.generated
     */
    public void setJpuzTime(String jpuzTime) {
        this.jpuzTime = jpuzTime == null ? null : jpuzTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_mis_jpuz_user.jpuz_sturts
     *
     * @return the value of view_mis_jpuz_user.jpuz_sturts
     *
     * @mbg.generated
     */
    public String getJpuzSturts() {
        return jpuzSturts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_mis_jpuz_user.jpuz_sturts
     *
     * @param jpuzSturts the value for view_mis_jpuz_user.jpuz_sturts
     *
     * @mbg.generated
     */
    public void setJpuzSturts(String jpuzSturts) {
        this.jpuzSturts = jpuzSturts == null ? null : jpuzSturts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_mis_jpuz_user.mis_tilte
     *
     * @return the value of view_mis_jpuz_user.mis_tilte
     *
     * @mbg.generated
     */
    public String getMisTilte() {
        return misTilte;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_mis_jpuz_user.mis_tilte
     *
     * @param misTilte the value for view_mis_jpuz_user.mis_tilte
     *
     * @mbg.generated
     */
    public void setMisTilte(String misTilte) {
        this.misTilte = misTilte == null ? null : misTilte.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_mis_jpuz_user.mis_content
     *
     * @return the value of view_mis_jpuz_user.mis_content
     *
     * @mbg.generated
     */
    public String getMisContent() {
        return misContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_mis_jpuz_user.mis_content
     *
     * @param misContent the value for view_mis_jpuz_user.mis_content
     *
     * @mbg.generated
     */
    public void setMisContent(String misContent) {
        this.misContent = misContent == null ? null : misContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_mis_jpuz_user.mis_time1
     *
     * @return the value of view_mis_jpuz_user.mis_time1
     *
     * @mbg.generated
     */
    public String getMisTime1() {
        return misTime1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_mis_jpuz_user.mis_time1
     *
     * @param misTime1 the value for view_mis_jpuz_user.mis_time1
     *
     * @mbg.generated
     */
    public void setMisTime1(String misTime1) {
        this.misTime1 = misTime1 == null ? null : misTime1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_mis_jpuz_user.mis_time2
     *
     * @return the value of view_mis_jpuz_user.mis_time2
     *
     * @mbg.generated
     */
    public String getMisTime2() {
        return misTime2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_mis_jpuz_user.mis_time2
     *
     * @param misTime2 the value for view_mis_jpuz_user.mis_time2
     *
     * @mbg.generated
     */
    public void setMisTime2(String misTime2) {
        this.misTime2 = misTime2 == null ? null : misTime2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_mis_jpuz_user.mis_struts
     *
     * @return the value of view_mis_jpuz_user.mis_struts
     *
     * @mbg.generated
     */
    public Integer getMisStruts() {
        return misStruts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_mis_jpuz_user.mis_struts
     *
     * @param misStruts the value for view_mis_jpuz_user.mis_struts
     *
     * @mbg.generated
     */
    public void setMisStruts(Integer misStruts) {
        this.misStruts = misStruts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_mis_jpuz_user.mis_xuqqnum
     *
     * @return the value of view_mis_jpuz_user.mis_xuqqnum
     *
     * @mbg.generated
     */
    public Integer getMisXuqqnum() {
        return misXuqqnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_mis_jpuz_user.mis_xuqqnum
     *
     * @param misXuqqnum the value for view_mis_jpuz_user.mis_xuqqnum
     *
     * @mbg.generated
     */
    public void setMisXuqqnum(Integer misXuqqnum) {
        this.misXuqqnum = misXuqqnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_mis_jpuz_user.mis_money
     *
     * @return the value of view_mis_jpuz_user.mis_money
     *
     * @mbg.generated
     */
    public Float getMisMoney() {
        return misMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_mis_jpuz_user.mis_money
     *
     * @param misMoney the value for view_mis_jpuz_user.mis_money
     *
     * @mbg.generated
     */
    public void setMisMoney(Float misMoney) {
        this.misMoney = misMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_mis_jpuz_user.user_imgurl
     *
     * @return the value of view_mis_jpuz_user.user_imgurl
     *
     * @mbg.generated
     */
    public String getUserImgurl() {
        return userImgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_mis_jpuz_user.user_imgurl
     *
     * @param userImgurl the value for view_mis_jpuz_user.user_imgurl
     *
     * @mbg.generated
     */
    public void setUserImgurl(String userImgurl) {
        this.userImgurl = userImgurl == null ? null : userImgurl.trim();
    }
}