package com.qingxun.pub.generate.pojo;

import java.util.ArrayList;
import java.util.List;

public class ViewMisJpuzUfqkExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table view_mis_jpuz_ufqk
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table view_mis_jpuz_ufqk
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table view_mis_jpuz_ufqk
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_mis_jpuz_ufqk
     *
     * @mbg.generated
     */
    public ViewMisJpuzUfqkExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_mis_jpuz_ufqk
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_mis_jpuz_ufqk
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_mis_jpuz_ufqk
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_mis_jpuz_ufqk
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_mis_jpuz_ufqk
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_mis_jpuz_ufqk
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_mis_jpuz_ufqk
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_mis_jpuz_ufqk
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_mis_jpuz_ufqk
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_mis_jpuz_ufqk
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table view_mis_jpuz_ufqk
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("_id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("_id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("_id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("_id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("_id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("_id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("_id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("_id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("_id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("_id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("_id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("_id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andFaqiIdIsNull() {
            addCriterion("faqi_id is null");
            return (Criteria) this;
        }

        public Criteria andFaqiIdIsNotNull() {
            addCriterion("faqi_id is not null");
            return (Criteria) this;
        }

        public Criteria andFaqiIdEqualTo(Integer value) {
            addCriterion("faqi_id =", value, "faqiId");
            return (Criteria) this;
        }

        public Criteria andFaqiIdNotEqualTo(Integer value) {
            addCriterion("faqi_id <>", value, "faqiId");
            return (Criteria) this;
        }

        public Criteria andFaqiIdGreaterThan(Integer value) {
            addCriterion("faqi_id >", value, "faqiId");
            return (Criteria) this;
        }

        public Criteria andFaqiIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("faqi_id >=", value, "faqiId");
            return (Criteria) this;
        }

        public Criteria andFaqiIdLessThan(Integer value) {
            addCriterion("faqi_id <", value, "faqiId");
            return (Criteria) this;
        }

        public Criteria andFaqiIdLessThanOrEqualTo(Integer value) {
            addCriterion("faqi_id <=", value, "faqiId");
            return (Criteria) this;
        }

        public Criteria andFaqiIdIn(List<Integer> values) {
            addCriterion("faqi_id in", values, "faqiId");
            return (Criteria) this;
        }

        public Criteria andFaqiIdNotIn(List<Integer> values) {
            addCriterion("faqi_id not in", values, "faqiId");
            return (Criteria) this;
        }

        public Criteria andFaqiIdBetween(Integer value1, Integer value2) {
            addCriterion("faqi_id between", value1, value2, "faqiId");
            return (Criteria) this;
        }

        public Criteria andFaqiIdNotBetween(Integer value1, Integer value2) {
            addCriterion("faqi_id not between", value1, value2, "faqiId");
            return (Criteria) this;
        }

        public Criteria andUserImgurlIsNull() {
            addCriterion("user_imgurl is null");
            return (Criteria) this;
        }

        public Criteria andUserImgurlIsNotNull() {
            addCriterion("user_imgurl is not null");
            return (Criteria) this;
        }

        public Criteria andUserImgurlEqualTo(String value) {
            addCriterion("user_imgurl =", value, "userImgurl");
            return (Criteria) this;
        }

        public Criteria andUserImgurlNotEqualTo(String value) {
            addCriterion("user_imgurl <>", value, "userImgurl");
            return (Criteria) this;
        }

        public Criteria andUserImgurlGreaterThan(String value) {
            addCriterion("user_imgurl >", value, "userImgurl");
            return (Criteria) this;
        }

        public Criteria andUserImgurlGreaterThanOrEqualTo(String value) {
            addCriterion("user_imgurl >=", value, "userImgurl");
            return (Criteria) this;
        }

        public Criteria andUserImgurlLessThan(String value) {
            addCriterion("user_imgurl <", value, "userImgurl");
            return (Criteria) this;
        }

        public Criteria andUserImgurlLessThanOrEqualTo(String value) {
            addCriterion("user_imgurl <=", value, "userImgurl");
            return (Criteria) this;
        }

        public Criteria andUserImgurlLike(String value) {
            addCriterion("user_imgurl like", value, "userImgurl");
            return (Criteria) this;
        }

        public Criteria andUserImgurlNotLike(String value) {
            addCriterion("user_imgurl not like", value, "userImgurl");
            return (Criteria) this;
        }

        public Criteria andUserImgurlIn(List<String> values) {
            addCriterion("user_imgurl in", values, "userImgurl");
            return (Criteria) this;
        }

        public Criteria andUserImgurlNotIn(List<String> values) {
            addCriterion("user_imgurl not in", values, "userImgurl");
            return (Criteria) this;
        }

        public Criteria andUserImgurlBetween(String value1, String value2) {
            addCriterion("user_imgurl between", value1, value2, "userImgurl");
            return (Criteria) this;
        }

        public Criteria andUserImgurlNotBetween(String value1, String value2) {
            addCriterion("user_imgurl not between", value1, value2, "userImgurl");
            return (Criteria) this;
        }

        public Criteria andMisTilteIsNull() {
            addCriterion("mis_tilte is null");
            return (Criteria) this;
        }

        public Criteria andMisTilteIsNotNull() {
            addCriterion("mis_tilte is not null");
            return (Criteria) this;
        }

        public Criteria andMisTilteEqualTo(String value) {
            addCriterion("mis_tilte =", value, "misTilte");
            return (Criteria) this;
        }

        public Criteria andMisTilteNotEqualTo(String value) {
            addCriterion("mis_tilte <>", value, "misTilte");
            return (Criteria) this;
        }

        public Criteria andMisTilteGreaterThan(String value) {
            addCriterion("mis_tilte >", value, "misTilte");
            return (Criteria) this;
        }

        public Criteria andMisTilteGreaterThanOrEqualTo(String value) {
            addCriterion("mis_tilte >=", value, "misTilte");
            return (Criteria) this;
        }

        public Criteria andMisTilteLessThan(String value) {
            addCriterion("mis_tilte <", value, "misTilte");
            return (Criteria) this;
        }

        public Criteria andMisTilteLessThanOrEqualTo(String value) {
            addCriterion("mis_tilte <=", value, "misTilte");
            return (Criteria) this;
        }

        public Criteria andMisTilteLike(String value) {
            addCriterion("mis_tilte like", value, "misTilte");
            return (Criteria) this;
        }

        public Criteria andMisTilteNotLike(String value) {
            addCriterion("mis_tilte not like", value, "misTilte");
            return (Criteria) this;
        }

        public Criteria andMisTilteIn(List<String> values) {
            addCriterion("mis_tilte in", values, "misTilte");
            return (Criteria) this;
        }

        public Criteria andMisTilteNotIn(List<String> values) {
            addCriterion("mis_tilte not in", values, "misTilte");
            return (Criteria) this;
        }

        public Criteria andMisTilteBetween(String value1, String value2) {
            addCriterion("mis_tilte between", value1, value2, "misTilte");
            return (Criteria) this;
        }

        public Criteria andMisTilteNotBetween(String value1, String value2) {
            addCriterion("mis_tilte not between", value1, value2, "misTilte");
            return (Criteria) this;
        }

        public Criteria andJpuzSturtsIsNull() {
            addCriterion("jpuz_sturts is null");
            return (Criteria) this;
        }

        public Criteria andJpuzSturtsIsNotNull() {
            addCriterion("jpuz_sturts is not null");
            return (Criteria) this;
        }

        public Criteria andJpuzSturtsEqualTo(String value) {
            addCriterion("jpuz_sturts =", value, "jpuzSturts");
            return (Criteria) this;
        }

        public Criteria andJpuzSturtsNotEqualTo(String value) {
            addCriterion("jpuz_sturts <>", value, "jpuzSturts");
            return (Criteria) this;
        }

        public Criteria andJpuzSturtsGreaterThan(String value) {
            addCriterion("jpuz_sturts >", value, "jpuzSturts");
            return (Criteria) this;
        }

        public Criteria andJpuzSturtsGreaterThanOrEqualTo(String value) {
            addCriterion("jpuz_sturts >=", value, "jpuzSturts");
            return (Criteria) this;
        }

        public Criteria andJpuzSturtsLessThan(String value) {
            addCriterion("jpuz_sturts <", value, "jpuzSturts");
            return (Criteria) this;
        }

        public Criteria andJpuzSturtsLessThanOrEqualTo(String value) {
            addCriterion("jpuz_sturts <=", value, "jpuzSturts");
            return (Criteria) this;
        }

        public Criteria andJpuzSturtsLike(String value) {
            addCriterion("jpuz_sturts like", value, "jpuzSturts");
            return (Criteria) this;
        }

        public Criteria andJpuzSturtsNotLike(String value) {
            addCriterion("jpuz_sturts not like", value, "jpuzSturts");
            return (Criteria) this;
        }

        public Criteria andJpuzSturtsIn(List<String> values) {
            addCriterion("jpuz_sturts in", values, "jpuzSturts");
            return (Criteria) this;
        }

        public Criteria andJpuzSturtsNotIn(List<String> values) {
            addCriterion("jpuz_sturts not in", values, "jpuzSturts");
            return (Criteria) this;
        }

        public Criteria andJpuzSturtsBetween(String value1, String value2) {
            addCriterion("jpuz_sturts between", value1, value2, "jpuzSturts");
            return (Criteria) this;
        }

        public Criteria andJpuzSturtsNotBetween(String value1, String value2) {
            addCriterion("jpuz_sturts not between", value1, value2, "jpuzSturts");
            return (Criteria) this;
        }

        public Criteria andJpuzTimeIsNull() {
            addCriterion("jpuz_time is null");
            return (Criteria) this;
        }

        public Criteria andJpuzTimeIsNotNull() {
            addCriterion("jpuz_time is not null");
            return (Criteria) this;
        }

        public Criteria andJpuzTimeEqualTo(String value) {
            addCriterion("jpuz_time =", value, "jpuzTime");
            return (Criteria) this;
        }

        public Criteria andJpuzTimeNotEqualTo(String value) {
            addCriterion("jpuz_time <>", value, "jpuzTime");
            return (Criteria) this;
        }

        public Criteria andJpuzTimeGreaterThan(String value) {
            addCriterion("jpuz_time >", value, "jpuzTime");
            return (Criteria) this;
        }

        public Criteria andJpuzTimeGreaterThanOrEqualTo(String value) {
            addCriterion("jpuz_time >=", value, "jpuzTime");
            return (Criteria) this;
        }

        public Criteria andJpuzTimeLessThan(String value) {
            addCriterion("jpuz_time <", value, "jpuzTime");
            return (Criteria) this;
        }

        public Criteria andJpuzTimeLessThanOrEqualTo(String value) {
            addCriterion("jpuz_time <=", value, "jpuzTime");
            return (Criteria) this;
        }

        public Criteria andJpuzTimeLike(String value) {
            addCriterion("jpuz_time like", value, "jpuzTime");
            return (Criteria) this;
        }

        public Criteria andJpuzTimeNotLike(String value) {
            addCriterion("jpuz_time not like", value, "jpuzTime");
            return (Criteria) this;
        }

        public Criteria andJpuzTimeIn(List<String> values) {
            addCriterion("jpuz_time in", values, "jpuzTime");
            return (Criteria) this;
        }

        public Criteria andJpuzTimeNotIn(List<String> values) {
            addCriterion("jpuz_time not in", values, "jpuzTime");
            return (Criteria) this;
        }

        public Criteria andJpuzTimeBetween(String value1, String value2) {
            addCriterion("jpuz_time between", value1, value2, "jpuzTime");
            return (Criteria) this;
        }

        public Criteria andJpuzTimeNotBetween(String value1, String value2) {
            addCriterion("jpuz_time not between", value1, value2, "jpuzTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table view_mis_jpuz_ufqk
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table view_mis_jpuz_ufqk
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}