package com.qingxun.pub.generate.pojo;

public class ViewMisJpuzUfqk {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_mis_jpuz_ufqk._id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_mis_jpuz_ufqk.faqi_id
     *
     * @mbg.generated
     */
    private Integer faqiId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_mis_jpuz_ufqk.user_imgurl
     *
     * @mbg.generated
     */
    private String userImgurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_mis_jpuz_ufqk.mis_tilte
     *
     * @mbg.generated
     */
    private String misTilte;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_mis_jpuz_ufqk.jpuz_sturts
     *
     * @mbg.generated
     */
    private String jpuzSturts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_mis_jpuz_ufqk.jpuz_time
     *
     * @mbg.generated
     */
    private String jpuzTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_mis_jpuz_ufqk._id
     *
     * @return the value of view_mis_jpuz_ufqk._id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_mis_jpuz_ufqk._id
     *
     * @param id the value for view_mis_jpuz_ufqk._id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_mis_jpuz_ufqk.faqi_id
     *
     * @return the value of view_mis_jpuz_ufqk.faqi_id
     *
     * @mbg.generated
     */
    public Integer getFaqiId() {
        return faqiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_mis_jpuz_ufqk.faqi_id
     *
     * @param faqiId the value for view_mis_jpuz_ufqk.faqi_id
     *
     * @mbg.generated
     */
    public void setFaqiId(Integer faqiId) {
        this.faqiId = faqiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_mis_jpuz_ufqk.user_imgurl
     *
     * @return the value of view_mis_jpuz_ufqk.user_imgurl
     *
     * @mbg.generated
     */
    public String getUserImgurl() {
        return userImgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_mis_jpuz_ufqk.user_imgurl
     *
     * @param userImgurl the value for view_mis_jpuz_ufqk.user_imgurl
     *
     * @mbg.generated
     */
    public void setUserImgurl(String userImgurl) {
        this.userImgurl = userImgurl == null ? null : userImgurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_mis_jpuz_ufqk.mis_tilte
     *
     * @return the value of view_mis_jpuz_ufqk.mis_tilte
     *
     * @mbg.generated
     */
    public String getMisTilte() {
        return misTilte;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_mis_jpuz_ufqk.mis_tilte
     *
     * @param misTilte the value for view_mis_jpuz_ufqk.mis_tilte
     *
     * @mbg.generated
     */
    public void setMisTilte(String misTilte) {
        this.misTilte = misTilte == null ? null : misTilte.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_mis_jpuz_ufqk.jpuz_sturts
     *
     * @return the value of view_mis_jpuz_ufqk.jpuz_sturts
     *
     * @mbg.generated
     */
    public String getJpuzSturts() {
        return jpuzSturts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_mis_jpuz_ufqk.jpuz_sturts
     *
     * @param jpuzSturts the value for view_mis_jpuz_ufqk.jpuz_sturts
     *
     * @mbg.generated
     */
    public void setJpuzSturts(String jpuzSturts) {
        this.jpuzSturts = jpuzSturts == null ? null : jpuzSturts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_mis_jpuz_ufqk.jpuz_time
     *
     * @return the value of view_mis_jpuz_ufqk.jpuz_time
     *
     * @mbg.generated
     */
    public String getJpuzTime() {
        return jpuzTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_mis_jpuz_ufqk.jpuz_time
     *
     * @param jpuzTime the value for view_mis_jpuz_ufqk.jpuz_time
     *
     * @mbg.generated
     */
    public void setJpuzTime(String jpuzTime) {
        this.jpuzTime = jpuzTime == null ? null : jpuzTime.trim();
    }
}