package com.qingxun.pub.generate.dao;

import com.qingxun.pub.generate.pojo.CommodityType1;
import com.qingxun.pub.generate.pojo.CommodityType1Example;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface CommodityType1Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_type1
     *
     * @mbg.generated
     */
    @SelectProvider(type=CommodityType1SqlProvider.class, method="countByExample")
    long countByExample(CommodityType1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_type1
     *
     * @mbg.generated
     */
    @DeleteProvider(type=CommodityType1SqlProvider.class, method="deleteByExample")
    int deleteByExample(CommodityType1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_type1
     *
     * @mbg.generated
     */
    @Delete({
        "delete from commodity_type1",
        "where _id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_type1
     *
     * @mbg.generated
     */
    @Insert({
        "insert into commodity_type1 (_id, type1_id, ",
        "mer_id, type1_name)",
        "values (#{id,jdbcType=INTEGER}, #{type1Id,jdbcType=INTEGER}, ",
        "#{merId,jdbcType=INTEGER}, #{type1Name,jdbcType=VARCHAR})"
    })
    int insert(CommodityType1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_type1
     *
     * @mbg.generated
     */
    @InsertProvider(type=CommodityType1SqlProvider.class, method="insertSelective")
    int insertSelective(CommodityType1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_type1
     *
     * @mbg.generated
     */
    @SelectProvider(type=CommodityType1SqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="_id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="type1_id", property="type1Id", jdbcType=JdbcType.INTEGER),
        @Result(column="mer_id", property="merId", jdbcType=JdbcType.INTEGER),
        @Result(column="type1_name", property="type1Name", jdbcType=JdbcType.VARCHAR)
    })
    List<CommodityType1> selectByExample(CommodityType1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_type1
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "_id, type1_id, mer_id, type1_name",
        "from commodity_type1",
        "where _id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="_id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="type1_id", property="type1Id", jdbcType=JdbcType.INTEGER),
        @Result(column="mer_id", property="merId", jdbcType=JdbcType.INTEGER),
        @Result(column="type1_name", property="type1Name", jdbcType=JdbcType.VARCHAR)
    })
    CommodityType1 selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_type1
     *
     * @mbg.generated
     */
    @UpdateProvider(type=CommodityType1SqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") CommodityType1 record, @Param("example") CommodityType1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_type1
     *
     * @mbg.generated
     */
    @UpdateProvider(type=CommodityType1SqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") CommodityType1 record, @Param("example") CommodityType1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_type1
     *
     * @mbg.generated
     */
    @UpdateProvider(type=CommodityType1SqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(CommodityType1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_type1
     *
     * @mbg.generated
     */
    @Update({
        "update commodity_type1",
        "set type1_id = #{type1Id,jdbcType=INTEGER},",
          "mer_id = #{merId,jdbcType=INTEGER},",
          "type1_name = #{type1Name,jdbcType=VARCHAR}",
        "where _id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(CommodityType1 record);
}