package com.qingxun.pub.generate.dao;

import com.qingxun.pub.generate.pojo.Commodity;
import com.qingxun.pub.generate.pojo.CommodityExample.Criteria;
import com.qingxun.pub.generate.pojo.CommodityExample.Criterion;
import com.qingxun.pub.generate.pojo.CommodityExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class CommoditySqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbg.generated
     */
    public String countByExample(CommodityExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("commodity");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbg.generated
     */
    public String deleteByExample(CommodityExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("commodity");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbg.generated
     */
    public String insertSelective(Commodity record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("commodity");
        
        if (record.getId() != null) {
            sql.VALUES("_id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getMarId() != null) {
            sql.VALUES("mar_id", "#{marId,jdbcType=INTEGER}");
        }
        
        if (record.getComId() != null) {
            sql.VALUES("com_id", "#{comId,jdbcType=INTEGER}");
        }
        
        if (record.getComImgurl() != null) {
            sql.VALUES("com_imgurl", "#{comImgurl,jdbcType=VARCHAR}");
        }
        
        if (record.getComStruts() != null) {
            sql.VALUES("com_struts", "#{comStruts,jdbcType=VARCHAR}");
        }
        
        if (record.getComTop() != null) {
            sql.VALUES("com_top", "#{comTop,jdbcType=INTEGER}");
        }
        
        if (record.getComTypyId1() != null) {
            sql.VALUES("com_typy_id1", "#{comTypyId1,jdbcType=INTEGER}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbg.generated
     */
    public String selectByExample(CommodityExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("_id");
        } else {
            sql.SELECT("_id");
        }
        sql.SELECT("mar_id");
        sql.SELECT("com_id");
        sql.SELECT("com_imgurl");
        sql.SELECT("com_struts");
        sql.SELECT("com_top");
        sql.SELECT("com_typy_id1");
        sql.FROM("commodity");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbg.generated
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        Commodity record = (Commodity) parameter.get("record");
        CommodityExample example = (CommodityExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("commodity");
        
        if (record.getId() != null) {
            sql.SET("_id = #{record.id,jdbcType=INTEGER}");
        }
        
        if (record.getMarId() != null) {
            sql.SET("mar_id = #{record.marId,jdbcType=INTEGER}");
        }
        
        if (record.getComId() != null) {
            sql.SET("com_id = #{record.comId,jdbcType=INTEGER}");
        }
        
        if (record.getComImgurl() != null) {
            sql.SET("com_imgurl = #{record.comImgurl,jdbcType=VARCHAR}");
        }
        
        if (record.getComStruts() != null) {
            sql.SET("com_struts = #{record.comStruts,jdbcType=VARCHAR}");
        }
        
        if (record.getComTop() != null) {
            sql.SET("com_top = #{record.comTop,jdbcType=INTEGER}");
        }
        
        if (record.getComTypyId1() != null) {
            sql.SET("com_typy_id1 = #{record.comTypyId1,jdbcType=INTEGER}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbg.generated
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("commodity");
        
        sql.SET("_id = #{record.id,jdbcType=INTEGER}");
        sql.SET("mar_id = #{record.marId,jdbcType=INTEGER}");
        sql.SET("com_id = #{record.comId,jdbcType=INTEGER}");
        sql.SET("com_imgurl = #{record.comImgurl,jdbcType=VARCHAR}");
        sql.SET("com_struts = #{record.comStruts,jdbcType=VARCHAR}");
        sql.SET("com_top = #{record.comTop,jdbcType=INTEGER}");
        sql.SET("com_typy_id1 = #{record.comTypyId1,jdbcType=INTEGER}");
        
        CommodityExample example = (CommodityExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(Commodity record) {
        SQL sql = new SQL();
        sql.UPDATE("commodity");
        
        if (record.getMarId() != null) {
            sql.SET("mar_id = #{marId,jdbcType=INTEGER}");
        }
        
        if (record.getComId() != null) {
            sql.SET("com_id = #{comId,jdbcType=INTEGER}");
        }
        
        if (record.getComImgurl() != null) {
            sql.SET("com_imgurl = #{comImgurl,jdbcType=VARCHAR}");
        }
        
        if (record.getComStruts() != null) {
            sql.SET("com_struts = #{comStruts,jdbcType=VARCHAR}");
        }
        
        if (record.getComTop() != null) {
            sql.SET("com_top = #{comTop,jdbcType=INTEGER}");
        }
        
        if (record.getComTypyId1() != null) {
            sql.SET("com_typy_id1 = #{comTypyId1,jdbcType=INTEGER}");
        }
        
        sql.WHERE("_id = #{id,jdbcType=INTEGER}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbg.generated
     */
    protected void applyWhere(SQL sql, CommodityExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}