package com.qingxun.pub.generate.dao;

import com.qingxun.pub.generate.pojo.Commodity;
import com.qingxun.pub.generate.pojo.CommodityExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface CommodityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbg.generated
     */
    @SelectProvider(type=CommoditySqlProvider.class, method="countByExample")
    long countByExample(CommodityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbg.generated
     */
    @DeleteProvider(type=CommoditySqlProvider.class, method="deleteByExample")
    int deleteByExample(CommodityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbg.generated
     */
    @Delete({
        "delete from commodity",
        "where _id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbg.generated
     */
    @Insert({
        "insert into commodity (_id, mar_id, ",
        "com_id, com_imgurl, ",
        "com_struts, com_top, ",
        "type1_id, com_name)",
        "values (#{id,jdbcType=INTEGER}, #{marId,jdbcType=INTEGER}, ",
        "#{comId,jdbcType=INTEGER}, #{comImgurl,jdbcType=VARCHAR}, ",
        "#{comStruts,jdbcType=VARCHAR}, #{comTop,jdbcType=INTEGER}, ",
        "#{type1Id,jdbcType=INTEGER}, #{comName,jdbcType=VARCHAR})"
    })
    int insert(Commodity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbg.generated
     */
    @InsertProvider(type=CommoditySqlProvider.class, method="insertSelective")
    int insertSelective(Commodity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbg.generated
     */
    @SelectProvider(type=CommoditySqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="_id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="mar_id", property="marId", jdbcType=JdbcType.INTEGER),
        @Result(column="com_id", property="comId", jdbcType=JdbcType.INTEGER),
        @Result(column="com_imgurl", property="comImgurl", jdbcType=JdbcType.VARCHAR),
        @Result(column="com_struts", property="comStruts", jdbcType=JdbcType.VARCHAR),
        @Result(column="com_top", property="comTop", jdbcType=JdbcType.INTEGER),
        @Result(column="type1_id", property="type1Id", jdbcType=JdbcType.INTEGER),
        @Result(column="com_name", property="comName", jdbcType=JdbcType.VARCHAR)
    })
    List<Commodity> selectByExample(CommodityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "_id, mar_id, com_id, com_imgurl, com_struts, com_top, type1_id, com_name",
        "from commodity",
        "where _id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="_id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="mar_id", property="marId", jdbcType=JdbcType.INTEGER),
        @Result(column="com_id", property="comId", jdbcType=JdbcType.INTEGER),
        @Result(column="com_imgurl", property="comImgurl", jdbcType=JdbcType.VARCHAR),
        @Result(column="com_struts", property="comStruts", jdbcType=JdbcType.VARCHAR),
        @Result(column="com_top", property="comTop", jdbcType=JdbcType.INTEGER),
        @Result(column="type1_id", property="type1Id", jdbcType=JdbcType.INTEGER),
        @Result(column="com_name", property="comName", jdbcType=JdbcType.VARCHAR)
    })
    Commodity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbg.generated
     */
    @UpdateProvider(type=CommoditySqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Commodity record, @Param("example") CommodityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbg.generated
     */
    @UpdateProvider(type=CommoditySqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Commodity record, @Param("example") CommodityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbg.generated
     */
    @UpdateProvider(type=CommoditySqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Commodity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbg.generated
     */
    @Update({
        "update commodity",
        "set mar_id = #{marId,jdbcType=INTEGER},",
          "com_id = #{comId,jdbcType=INTEGER},",
          "com_imgurl = #{comImgurl,jdbcType=VARCHAR},",
          "com_struts = #{comStruts,jdbcType=VARCHAR},",
          "com_top = #{comTop,jdbcType=INTEGER},",
          "type1_id = #{type1Id,jdbcType=INTEGER},",
          "com_name = #{comName,jdbcType=VARCHAR}",
        "where _id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Commodity record);
}