package com.qingxun.pub.generate.dao;

import com.qingxun.pub.generate.pojo.CommodityType2;
import com.qingxun.pub.generate.pojo.CommodityType2Example.Criteria;
import com.qingxun.pub.generate.pojo.CommodityType2Example.Criterion;
import com.qingxun.pub.generate.pojo.CommodityType2Example;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class CommodityType2SqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_type2
     *
     * @mbg.generated
     */
    public String countByExample(CommodityType2Example example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("commodity_type2");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_type2
     *
     * @mbg.generated
     */
    public String deleteByExample(CommodityType2Example example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("commodity_type2");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_type2
     *
     * @mbg.generated
     */
    public String insertSelective(CommodityType2 record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("commodity_type2");
        
        if (record.getId() != null) {
            sql.VALUES("_id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getType2Id() != null) {
            sql.VALUES("type2_id", "#{type2Id,jdbcType=INTEGER}");
        }
        
        if (record.getType1Id() != null) {
            sql.VALUES("type1_id", "#{type1Id,jdbcType=INTEGER}");
        }
        
        if (record.getType2Name() != null) {
            sql.VALUES("type2_name", "#{type2Name,jdbcType=VARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_type2
     *
     * @mbg.generated
     */
    public String selectByExample(CommodityType2Example example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("_id");
        } else {
            sql.SELECT("_id");
        }
        sql.SELECT("type2_id");
        sql.SELECT("type1_id");
        sql.SELECT("type2_name");
        sql.FROM("commodity_type2");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_type2
     *
     * @mbg.generated
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        CommodityType2 record = (CommodityType2) parameter.get("record");
        CommodityType2Example example = (CommodityType2Example) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("commodity_type2");
        
        if (record.getId() != null) {
            sql.SET("_id = #{record.id,jdbcType=INTEGER}");
        }
        
        if (record.getType2Id() != null) {
            sql.SET("type2_id = #{record.type2Id,jdbcType=INTEGER}");
        }
        
        if (record.getType1Id() != null) {
            sql.SET("type1_id = #{record.type1Id,jdbcType=INTEGER}");
        }
        
        if (record.getType2Name() != null) {
            sql.SET("type2_name = #{record.type2Name,jdbcType=VARCHAR}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_type2
     *
     * @mbg.generated
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("commodity_type2");
        
        sql.SET("_id = #{record.id,jdbcType=INTEGER}");
        sql.SET("type2_id = #{record.type2Id,jdbcType=INTEGER}");
        sql.SET("type1_id = #{record.type1Id,jdbcType=INTEGER}");
        sql.SET("type2_name = #{record.type2Name,jdbcType=VARCHAR}");
        
        CommodityType2Example example = (CommodityType2Example) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_type2
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(CommodityType2 record) {
        SQL sql = new SQL();
        sql.UPDATE("commodity_type2");
        
        if (record.getType2Id() != null) {
            sql.SET("type2_id = #{type2Id,jdbcType=INTEGER}");
        }
        
        if (record.getType1Id() != null) {
            sql.SET("type1_id = #{type1Id,jdbcType=INTEGER}");
        }
        
        if (record.getType2Name() != null) {
            sql.SET("type2_name = #{type2Name,jdbcType=VARCHAR}");
        }
        
        sql.WHERE("_id = #{id,jdbcType=INTEGER}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_type2
     *
     * @mbg.generated
     */
    protected void applyWhere(SQL sql, CommodityType2Example example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}