package com.qingxun.pub.generate.dao;

import com.qingxun.pub.generate.pojo.MissionJpuz;
import com.qingxun.pub.generate.pojo.MissionJpuzExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface MissionJpuzMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission_jpuz
     *
     * @mbg.generated
     */
    @SelectProvider(type=MissionJpuzSqlProvider.class, method="countByExample")
    long countByExample(MissionJpuzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission_jpuz
     *
     * @mbg.generated
     */
    @DeleteProvider(type=MissionJpuzSqlProvider.class, method="deleteByExample")
    int deleteByExample(MissionJpuzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission_jpuz
     *
     * @mbg.generated
     */
    @Delete({
        "delete from mission_jpuz",
        "where _id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission_jpuz
     *
     * @mbg.generated
     */
    @Insert({
        "insert into mission_jpuz (_id, jpuz_id, ",
        "user_id, jpuz_time, ",
        "jpuz_sturts)",
        "values (#{id,jdbcType=INTEGER}, #{jpuzId,jdbcType=INTEGER}, ",
        "#{userId,jdbcType=INTEGER}, #{jpuzTime,jdbcType=VARCHAR}, ",
        "#{jpuzSturts,jdbcType=VARCHAR})"
    })
    int insert(MissionJpuz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission_jpuz
     *
     * @mbg.generated
     */
    @InsertProvider(type=MissionJpuzSqlProvider.class, method="insertSelective")
    int insertSelective(MissionJpuz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission_jpuz
     *
     * @mbg.generated
     */
    @SelectProvider(type=MissionJpuzSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="_id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="jpuz_id", property="jpuzId", jdbcType=JdbcType.INTEGER),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.INTEGER),
        @Result(column="jpuz_time", property="jpuzTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="jpuz_sturts", property="jpuzSturts", jdbcType=JdbcType.VARCHAR)
    })
    List<MissionJpuz> selectByExample(MissionJpuzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission_jpuz
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "_id, jpuz_id, user_id, jpuz_time, jpuz_sturts",
        "from mission_jpuz",
        "where _id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="_id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="jpuz_id", property="jpuzId", jdbcType=JdbcType.INTEGER),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.INTEGER),
        @Result(column="jpuz_time", property="jpuzTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="jpuz_sturts", property="jpuzSturts", jdbcType=JdbcType.VARCHAR)
    })
    MissionJpuz selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission_jpuz
     *
     * @mbg.generated
     */
    @UpdateProvider(type=MissionJpuzSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") MissionJpuz record, @Param("example") MissionJpuzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission_jpuz
     *
     * @mbg.generated
     */
    @UpdateProvider(type=MissionJpuzSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") MissionJpuz record, @Param("example") MissionJpuzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission_jpuz
     *
     * @mbg.generated
     */
    @UpdateProvider(type=MissionJpuzSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(MissionJpuz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission_jpuz
     *
     * @mbg.generated
     */
    @Update({
        "update mission_jpuz",
        "set jpuz_id = #{jpuzId,jdbcType=INTEGER},",
          "user_id = #{userId,jdbcType=INTEGER},",
          "jpuz_time = #{jpuzTime,jdbcType=VARCHAR},",
          "jpuz_sturts = #{jpuzSturts,jdbcType=VARCHAR}",
        "where _id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(MissionJpuz record);
}