package com.qingxun.pub.generate.dao;

import com.qingxun.pub.generate.pojo.UserUserOth;
import com.qingxun.pub.generate.pojo.UserUserOthExample.Criteria;
import com.qingxun.pub.generate.pojo.UserUserOthExample.Criterion;
import com.qingxun.pub.generate.pojo.UserUserOthExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class UserUserOthSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_user_oth
     *
     * @mbg.generated
     */
    public String countByExample(UserUserOthExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("user_user_oth");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_user_oth
     *
     * @mbg.generated
     */
    public String deleteByExample(UserUserOthExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("user_user_oth");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_user_oth
     *
     * @mbg.generated
     */
    public String insertSelective(UserUserOth record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("user_user_oth");
        
        if (record.getId() != null) {
            sql.VALUES("_id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getOthId() != null) {
            sql.VALUES("oth_id", "#{othId,jdbcType=INTEGER}");
        }
        
        if (record.getOthPhone() != null) {
            sql.VALUES("oth_phone", "#{othPhone,jdbcType=VARCHAR}");
        }
        
        if (record.getOthSuue() != null) {
            sql.VALUES("oth_suue", "#{othSuue,jdbcType=VARCHAR}");
        }
        
        if (record.getOthSchool() != null) {
            sql.VALUES("oth_school", "#{othSchool,jdbcType=VARCHAR}");
        }
        
        if (record.getUserId() != null) {
            sql.VALUES("user_id", "#{userId,jdbcType=INTEGER}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_user_oth
     *
     * @mbg.generated
     */
    public String selectByExample(UserUserOthExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("_id");
        } else {
            sql.SELECT("_id");
        }
        sql.SELECT("oth_id");
        sql.SELECT("oth_phone");
        sql.SELECT("oth_suue");
        sql.SELECT("oth_school");
        sql.SELECT("user_id");
        sql.FROM("user_user_oth");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_user_oth
     *
     * @mbg.generated
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        UserUserOth record = (UserUserOth) parameter.get("record");
        UserUserOthExample example = (UserUserOthExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("user_user_oth");
        
        if (record.getId() != null) {
            sql.SET("_id = #{record.id,jdbcType=INTEGER}");
        }
        
        if (record.getOthId() != null) {
            sql.SET("oth_id = #{record.othId,jdbcType=INTEGER}");
        }
        
        if (record.getOthPhone() != null) {
            sql.SET("oth_phone = #{record.othPhone,jdbcType=VARCHAR}");
        }
        
        if (record.getOthSuue() != null) {
            sql.SET("oth_suue = #{record.othSuue,jdbcType=VARCHAR}");
        }
        
        if (record.getOthSchool() != null) {
            sql.SET("oth_school = #{record.othSchool,jdbcType=VARCHAR}");
        }
        
        if (record.getUserId() != null) {
            sql.SET("user_id = #{record.userId,jdbcType=INTEGER}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_user_oth
     *
     * @mbg.generated
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("user_user_oth");
        
        sql.SET("_id = #{record.id,jdbcType=INTEGER}");
        sql.SET("oth_id = #{record.othId,jdbcType=INTEGER}");
        sql.SET("oth_phone = #{record.othPhone,jdbcType=VARCHAR}");
        sql.SET("oth_suue = #{record.othSuue,jdbcType=VARCHAR}");
        sql.SET("oth_school = #{record.othSchool,jdbcType=VARCHAR}");
        sql.SET("user_id = #{record.userId,jdbcType=INTEGER}");
        
        UserUserOthExample example = (UserUserOthExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_user_oth
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(UserUserOth record) {
        SQL sql = new SQL();
        sql.UPDATE("user_user_oth");
        
        if (record.getOthPhone() != null) {
            sql.SET("oth_phone = #{othPhone,jdbcType=VARCHAR}");
        }
        
        if (record.getOthSuue() != null) {
            sql.SET("oth_suue = #{othSuue,jdbcType=VARCHAR}");
        }
        
        if (record.getOthSchool() != null) {
            sql.SET("oth_school = #{othSchool,jdbcType=VARCHAR}");
        }
        
        if (record.getUserId() != null) {
            sql.SET("user_id = #{userId,jdbcType=INTEGER}");
        }
        
        sql.WHERE("_id = #{id,jdbcType=INTEGER}");
        sql.WHERE("oth_id = #{othId,jdbcType=INTEGER}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_user_oth
     *
     * @mbg.generated
     */
    protected void applyWhere(SQL sql, UserUserOthExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}