package com.qingxun.pub.generate.dao;

import com.qingxun.pub.generate.pojo.ViewMisJpuzUser;
import com.qingxun.pub.generate.pojo.ViewMisJpuzUserExample;
import java.util.List;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface ViewMisJpuzUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_mis_jpuz_user
     *
     * @mbg.generated
     */
    @SelectProvider(type=ViewMisJpuzUserSqlProvider.class, method="countByExample")
    long countByExample(ViewMisJpuzUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_mis_jpuz_user
     *
     * @mbg.generated
     */
    @DeleteProvider(type=ViewMisJpuzUserSqlProvider.class, method="deleteByExample")
    int deleteByExample(ViewMisJpuzUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_mis_jpuz_user
     *
     * @mbg.generated
     */
    @Insert({
        "insert into view_mis_jpuz_user (jpuz_id, user_id, ",
        "jpuz_time, jpuz_sturts, ",
        "mis_tilte, mis_content, ",
        "mis_time1, mis_time2, ",
        "mis_struts, mis_xuqqnum, ",
        "mis_money, user_imgurl)",
        "values (#{jpuzId,jdbcType=INTEGER}, #{userId,jdbcType=INTEGER}, ",
        "#{jpuzTime,jdbcType=VARCHAR}, #{jpuzSturts,jdbcType=VARCHAR}, ",
        "#{misTilte,jdbcType=VARCHAR}, #{misContent,jdbcType=VARCHAR}, ",
        "#{misTime1,jdbcType=VARCHAR}, #{misTime2,jdbcType=VARCHAR}, ",
        "#{misStruts,jdbcType=INTEGER}, #{misXuqqnum,jdbcType=INTEGER}, ",
        "#{misMoney,jdbcType=REAL}, #{userImgurl,jdbcType=VARCHAR})"
    })
    int insert(ViewMisJpuzUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_mis_jpuz_user
     *
     * @mbg.generated
     */
    @InsertProvider(type=ViewMisJpuzUserSqlProvider.class, method="insertSelective")
    int insertSelective(ViewMisJpuzUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_mis_jpuz_user
     *
     * @mbg.generated
     */
    @SelectProvider(type=ViewMisJpuzUserSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="jpuz_id", property="jpuzId", jdbcType=JdbcType.INTEGER),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.INTEGER),
        @Result(column="jpuz_time", property="jpuzTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="jpuz_sturts", property="jpuzSturts", jdbcType=JdbcType.VARCHAR),
        @Result(column="mis_tilte", property="misTilte", jdbcType=JdbcType.VARCHAR),
        @Result(column="mis_content", property="misContent", jdbcType=JdbcType.VARCHAR),
        @Result(column="mis_time1", property="misTime1", jdbcType=JdbcType.VARCHAR),
        @Result(column="mis_time2", property="misTime2", jdbcType=JdbcType.VARCHAR),
        @Result(column="mis_struts", property="misStruts", jdbcType=JdbcType.INTEGER),
        @Result(column="mis_xuqqnum", property="misXuqqnum", jdbcType=JdbcType.INTEGER),
        @Result(column="mis_money", property="misMoney", jdbcType=JdbcType.REAL),
        @Result(column="user_imgurl", property="userImgurl", jdbcType=JdbcType.VARCHAR)
    })
    List<ViewMisJpuzUser> selectByExample(ViewMisJpuzUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_mis_jpuz_user
     *
     * @mbg.generated
     */
    @UpdateProvider(type=ViewMisJpuzUserSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") ViewMisJpuzUser record, @Param("example") ViewMisJpuzUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_mis_jpuz_user
     *
     * @mbg.generated
     */
    @UpdateProvider(type=ViewMisJpuzUserSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") ViewMisJpuzUser record, @Param("example") ViewMisJpuzUserExample example);
}