package com.qingxun.pub.generate.dao;

import com.qingxun.pub.generate.pojo.ViewMisJpuzUser;
import com.qingxun.pub.generate.pojo.ViewMisJpuzUserExample.Criteria;
import com.qingxun.pub.generate.pojo.ViewMisJpuzUserExample.Criterion;
import com.qingxun.pub.generate.pojo.ViewMisJpuzUserExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class ViewMisJpuzUserSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_mis_jpuz_user
     *
     * @mbg.generated
     */
    public String countByExample(ViewMisJpuzUserExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("view_mis_jpuz_user");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_mis_jpuz_user
     *
     * @mbg.generated
     */
    public String deleteByExample(ViewMisJpuzUserExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("view_mis_jpuz_user");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_mis_jpuz_user
     *
     * @mbg.generated
     */
    public String insertSelective(ViewMisJpuzUser record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("view_mis_jpuz_user");
        
        if (record.getJpuzId() != null) {
            sql.VALUES("jpuz_id", "#{jpuzId,jdbcType=INTEGER}");
        }
        
        if (record.getUserId() != null) {
            sql.VALUES("user_id", "#{userId,jdbcType=INTEGER}");
        }
        
        if (record.getJpuzTime() != null) {
            sql.VALUES("jpuz_time", "#{jpuzTime,jdbcType=VARCHAR}");
        }
        
        if (record.getJpuzSturts() != null) {
            sql.VALUES("jpuz_sturts", "#{jpuzSturts,jdbcType=VARCHAR}");
        }
        
        if (record.getMisTilte() != null) {
            sql.VALUES("mis_tilte", "#{misTilte,jdbcType=VARCHAR}");
        }
        
        if (record.getMisContent() != null) {
            sql.VALUES("mis_content", "#{misContent,jdbcType=VARCHAR}");
        }
        
        if (record.getMisTime1() != null) {
            sql.VALUES("mis_time1", "#{misTime1,jdbcType=VARCHAR}");
        }
        
        if (record.getMisTime2() != null) {
            sql.VALUES("mis_time2", "#{misTime2,jdbcType=VARCHAR}");
        }
        
        if (record.getMisStruts() != null) {
            sql.VALUES("mis_struts", "#{misStruts,jdbcType=INTEGER}");
        }
        
        if (record.getMisXuqqnum() != null) {
            sql.VALUES("mis_xuqqnum", "#{misXuqqnum,jdbcType=INTEGER}");
        }
        
        if (record.getMisMoney() != null) {
            sql.VALUES("mis_money", "#{misMoney,jdbcType=REAL}");
        }
        
        if (record.getUserImgurl() != null) {
            sql.VALUES("user_imgurl", "#{userImgurl,jdbcType=VARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_mis_jpuz_user
     *
     * @mbg.generated
     */
    public String selectByExample(ViewMisJpuzUserExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("jpuz_id");
        } else {
            sql.SELECT("jpuz_id");
        }
        sql.SELECT("user_id");
        sql.SELECT("jpuz_time");
        sql.SELECT("jpuz_sturts");
        sql.SELECT("mis_tilte");
        sql.SELECT("mis_content");
        sql.SELECT("mis_time1");
        sql.SELECT("mis_time2");
        sql.SELECT("mis_struts");
        sql.SELECT("mis_xuqqnum");
        sql.SELECT("mis_money");
        sql.SELECT("user_imgurl");
        sql.FROM("view_mis_jpuz_user");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_mis_jpuz_user
     *
     * @mbg.generated
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        ViewMisJpuzUser record = (ViewMisJpuzUser) parameter.get("record");
        ViewMisJpuzUserExample example = (ViewMisJpuzUserExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("view_mis_jpuz_user");
        
        if (record.getJpuzId() != null) {
            sql.SET("jpuz_id = #{record.jpuzId,jdbcType=INTEGER}");
        }
        
        if (record.getUserId() != null) {
            sql.SET("user_id = #{record.userId,jdbcType=INTEGER}");
        }
        
        if (record.getJpuzTime() != null) {
            sql.SET("jpuz_time = #{record.jpuzTime,jdbcType=VARCHAR}");
        }
        
        if (record.getJpuzSturts() != null) {
            sql.SET("jpuz_sturts = #{record.jpuzSturts,jdbcType=VARCHAR}");
        }
        
        if (record.getMisTilte() != null) {
            sql.SET("mis_tilte = #{record.misTilte,jdbcType=VARCHAR}");
        }
        
        if (record.getMisContent() != null) {
            sql.SET("mis_content = #{record.misContent,jdbcType=VARCHAR}");
        }
        
        if (record.getMisTime1() != null) {
            sql.SET("mis_time1 = #{record.misTime1,jdbcType=VARCHAR}");
        }
        
        if (record.getMisTime2() != null) {
            sql.SET("mis_time2 = #{record.misTime2,jdbcType=VARCHAR}");
        }
        
        if (record.getMisStruts() != null) {
            sql.SET("mis_struts = #{record.misStruts,jdbcType=INTEGER}");
        }
        
        if (record.getMisXuqqnum() != null) {
            sql.SET("mis_xuqqnum = #{record.misXuqqnum,jdbcType=INTEGER}");
        }
        
        if (record.getMisMoney() != null) {
            sql.SET("mis_money = #{record.misMoney,jdbcType=REAL}");
        }
        
        if (record.getUserImgurl() != null) {
            sql.SET("user_imgurl = #{record.userImgurl,jdbcType=VARCHAR}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_mis_jpuz_user
     *
     * @mbg.generated
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("view_mis_jpuz_user");
        
        sql.SET("jpuz_id = #{record.jpuzId,jdbcType=INTEGER}");
        sql.SET("user_id = #{record.userId,jdbcType=INTEGER}");
        sql.SET("jpuz_time = #{record.jpuzTime,jdbcType=VARCHAR}");
        sql.SET("jpuz_sturts = #{record.jpuzSturts,jdbcType=VARCHAR}");
        sql.SET("mis_tilte = #{record.misTilte,jdbcType=VARCHAR}");
        sql.SET("mis_content = #{record.misContent,jdbcType=VARCHAR}");
        sql.SET("mis_time1 = #{record.misTime1,jdbcType=VARCHAR}");
        sql.SET("mis_time2 = #{record.misTime2,jdbcType=VARCHAR}");
        sql.SET("mis_struts = #{record.misStruts,jdbcType=INTEGER}");
        sql.SET("mis_xuqqnum = #{record.misXuqqnum,jdbcType=INTEGER}");
        sql.SET("mis_money = #{record.misMoney,jdbcType=REAL}");
        sql.SET("user_imgurl = #{record.userImgurl,jdbcType=VARCHAR}");
        
        ViewMisJpuzUserExample example = (ViewMisJpuzUserExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_mis_jpuz_user
     *
     * @mbg.generated
     */
    protected void applyWhere(SQL sql, ViewMisJpuzUserExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}