package com.qingxun.pub.generate.dao;

import com.qingxun.pub.generate.pojo.ViewMisAll;
import com.qingxun.pub.generate.pojo.ViewMisAllExample;
import java.util.List;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface ViewMisAllMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_mis_all
     *
     * @mbg.generated
     */
    @SelectProvider(type=ViewMisAllSqlProvider.class, method="countByExample")
    long countByExample(ViewMisAllExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_mis_all
     *
     * @mbg.generated
     */
    @DeleteProvider(type=ViewMisAllSqlProvider.class, method="deleteByExample")
    int deleteByExample(ViewMisAllExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_mis_all
     *
     * @mbg.generated
     */
    @Insert({
        "insert into view_mis_all (user_imgurl, faqi_id, ",
        "mis_content, mis_time1, ",
        "mis_time2, mis_struts, ",
        "mis_xuqqnum, mis_money, ",
        "mis_tilte, mis_top, ",
        "mis_id)",
        "values (#{userImgurl,jdbcType=VARCHAR}, #{faqiId,jdbcType=INTEGER}, ",
        "#{misContent,jdbcType=VARCHAR}, #{misTime1,jdbcType=VARCHAR}, ",
        "#{misTime2,jdbcType=VARCHAR}, #{misStruts,jdbcType=INTEGER}, ",
        "#{misXuqqnum,jdbcType=INTEGER}, #{misMoney,jdbcType=REAL}, ",
        "#{misTilte,jdbcType=VARCHAR}, #{misTop,jdbcType=INTEGER}, ",
        "#{misId,jdbcType=INTEGER})"
    })
    int insert(ViewMisAll record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_mis_all
     *
     * @mbg.generated
     */
    @InsertProvider(type=ViewMisAllSqlProvider.class, method="insertSelective")
    int insertSelective(ViewMisAll record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_mis_all
     *
     * @mbg.generated
     */
    @SelectProvider(type=ViewMisAllSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="user_imgurl", property="userImgurl", jdbcType=JdbcType.VARCHAR),
        @Result(column="faqi_id", property="faqiId", jdbcType=JdbcType.INTEGER),
        @Result(column="mis_content", property="misContent", jdbcType=JdbcType.VARCHAR),
        @Result(column="mis_time1", property="misTime1", jdbcType=JdbcType.VARCHAR),
        @Result(column="mis_time2", property="misTime2", jdbcType=JdbcType.VARCHAR),
        @Result(column="mis_struts", property="misStruts", jdbcType=JdbcType.INTEGER),
        @Result(column="mis_xuqqnum", property="misXuqqnum", jdbcType=JdbcType.INTEGER),
        @Result(column="mis_money", property="misMoney", jdbcType=JdbcType.REAL),
        @Result(column="mis_tilte", property="misTilte", jdbcType=JdbcType.VARCHAR),
        @Result(column="mis_top", property="misTop", jdbcType=JdbcType.INTEGER),
        @Result(column="mis_id", property="misId", jdbcType=JdbcType.INTEGER)
    })
    List<ViewMisAll> selectByExample(ViewMisAllExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_mis_all
     *
     * @mbg.generated
     */
    @UpdateProvider(type=ViewMisAllSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") ViewMisAll record, @Param("example") ViewMisAllExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_mis_all
     *
     * @mbg.generated
     */
    @UpdateProvider(type=ViewMisAllSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") ViewMisAll record, @Param("example") ViewMisAllExample example);
}