package com.qingxun.pub.generate.dao;

import com.qingxun.pub.generate.pojo.ViewMisJpuzUfqk;
import com.qingxun.pub.generate.pojo.ViewMisJpuzUfqkExample.Criteria;
import com.qingxun.pub.generate.pojo.ViewMisJpuzUfqkExample.Criterion;
import com.qingxun.pub.generate.pojo.ViewMisJpuzUfqkExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class ViewMisJpuzUfqkSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_mis_jpuz_ufqk
     *
     * @mbg.generated
     */
    public String countByExample(ViewMisJpuzUfqkExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("view_mis_jpuz_ufqk");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_mis_jpuz_ufqk
     *
     * @mbg.generated
     */
    public String deleteByExample(ViewMisJpuzUfqkExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("view_mis_jpuz_ufqk");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_mis_jpuz_ufqk
     *
     * @mbg.generated
     */
    public String insertSelective(ViewMisJpuzUfqk record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("view_mis_jpuz_ufqk");
        
        if (record.getId() != null) {
            sql.VALUES("_id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getFaqiId() != null) {
            sql.VALUES("faqi_id", "#{faqiId,jdbcType=INTEGER}");
        }
        
        if (record.getUserImgurl() != null) {
            sql.VALUES("user_imgurl", "#{userImgurl,jdbcType=VARCHAR}");
        }
        
        if (record.getMisTilte() != null) {
            sql.VALUES("mis_tilte", "#{misTilte,jdbcType=VARCHAR}");
        }
        
        if (record.getJpuzSturts() != null) {
            sql.VALUES("jpuz_sturts", "#{jpuzSturts,jdbcType=VARCHAR}");
        }
        
        if (record.getJpuzTime() != null) {
            sql.VALUES("jpuz_time", "#{jpuzTime,jdbcType=VARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_mis_jpuz_ufqk
     *
     * @mbg.generated
     */
    public String selectByExample(ViewMisJpuzUfqkExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("_id");
        } else {
            sql.SELECT("_id");
        }
        sql.SELECT("faqi_id");
        sql.SELECT("user_imgurl");
        sql.SELECT("mis_tilte");
        sql.SELECT("jpuz_sturts");
        sql.SELECT("jpuz_time");
        sql.FROM("view_mis_jpuz_ufqk");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_mis_jpuz_ufqk
     *
     * @mbg.generated
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        ViewMisJpuzUfqk record = (ViewMisJpuzUfqk) parameter.get("record");
        ViewMisJpuzUfqkExample example = (ViewMisJpuzUfqkExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("view_mis_jpuz_ufqk");
        
        if (record.getId() != null) {
            sql.SET("_id = #{record.id,jdbcType=INTEGER}");
        }
        
        if (record.getFaqiId() != null) {
            sql.SET("faqi_id = #{record.faqiId,jdbcType=INTEGER}");
        }
        
        if (record.getUserImgurl() != null) {
            sql.SET("user_imgurl = #{record.userImgurl,jdbcType=VARCHAR}");
        }
        
        if (record.getMisTilte() != null) {
            sql.SET("mis_tilte = #{record.misTilte,jdbcType=VARCHAR}");
        }
        
        if (record.getJpuzSturts() != null) {
            sql.SET("jpuz_sturts = #{record.jpuzSturts,jdbcType=VARCHAR}");
        }
        
        if (record.getJpuzTime() != null) {
            sql.SET("jpuz_time = #{record.jpuzTime,jdbcType=VARCHAR}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_mis_jpuz_ufqk
     *
     * @mbg.generated
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("view_mis_jpuz_ufqk");
        
        sql.SET("_id = #{record.id,jdbcType=INTEGER}");
        sql.SET("faqi_id = #{record.faqiId,jdbcType=INTEGER}");
        sql.SET("user_imgurl = #{record.userImgurl,jdbcType=VARCHAR}");
        sql.SET("mis_tilte = #{record.misTilte,jdbcType=VARCHAR}");
        sql.SET("jpuz_sturts = #{record.jpuzSturts,jdbcType=VARCHAR}");
        sql.SET("jpuz_time = #{record.jpuzTime,jdbcType=VARCHAR}");
        
        ViewMisJpuzUfqkExample example = (ViewMisJpuzUfqkExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_mis_jpuz_ufqk
     *
     * @mbg.generated
     */
    protected void applyWhere(SQL sql, ViewMisJpuzUfqkExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}